/**
 * seo/books-intro.js — an introduction for each of the 66 books, used by
 * bookPage() in render.js. Book pages were a chapter grid and nothing else;
 * these turn them into real pages and target the queries people actually
 * type ("who wrote hebrews", "book of james summary", "what is ecclesiastes
 * about"), which are also the questions AI assistants get asked.
 *
 * Fields per book (keyed by book slug):
 *   wrote    who wrote it. Where authorship is traditional or unknown, say so
 *            here — the page prints this verbatim, so never overstate it.
 *   when     approximate date. Rendered as "traditionally dated ..." because
 *            these are the conventional datings, not settled fact.
 *   theme    three or four words, used in the title tag and the facts row.
 *   summary  two sentences of plain description. No doctrinal argument.
 *   outline  [chapter range, label] — the shape of the book at a glance.
 *   keys     three references that must resolve in seo/data/kjv.json.
 */
export const BOOK_INTROS = {
  genesis: { wrote: "Moses, by long-standing tradition", when: "about 1400 BC", theme: "beginnings",
    summary: "Genesis is the book of beginnings — the heavens and the earth, mankind, marriage, sin, and God's promise to undo it. After the flood and the scattering at Babel, the story narrows to one family: Abraham, Isaac, Jacob, and Joseph.",
    outline: [["1–11", "Creation, the fall, the flood, the nations"], ["12–25", "Abraham"], ["25–36", "Isaac and Jacob"], ["37–50", "Joseph"]],
    keys: ["Genesis 1:1", "Genesis 3:15", "Genesis 50:20"] },
  exodus: { wrote: "Moses, by long-standing tradition", when: "about 1400 BC", theme: "redemption out of Egypt",
    summary: "Israel is enslaved in Egypt, and God delivers them by the hand of Moses, through the plagues and the Red Sea. At Sinai he gives them his law and the pattern for the tabernacle, so that he may dwell among them.",
    outline: [["1–12", "Slavery, Moses, and the plagues"], ["13–18", "The Red Sea and the wilderness"], ["19–24", "The law at Sinai"], ["25–40", "The tabernacle"]],
    keys: ["Exodus 3:14", "Exodus 14:14", "Exodus 20:3"] },
  leviticus: { wrote: "Moses, by long-standing tradition", when: "about 1400 BC", theme: "holiness and sacrifice",
    summary: "Leviticus is the handbook of worship for a people living near a holy God — the offerings, the priesthood, and the Day of Atonement. Its refrain is that God's people are to be holy because he is holy.",
    outline: [["1–7", "The offerings"], ["8–10", "The priesthood"], ["11–15", "Clean and unclean"], ["16", "The Day of Atonement"], ["17–27", "Holy living"]],
    keys: ["Leviticus 17:11", "Leviticus 19:2", "Leviticus 19:18"] },
  numbers: { wrote: "Moses, by long-standing tradition", when: "about 1400 BC", theme: "the wilderness years",
    summary: "Israel is numbered and organised for the march to Canaan, then refuses to enter at Kadesh and wanders for forty years. A new generation grows up and is brought at last to the edge of the promised land.",
    outline: [["1–10", "Numbered at Sinai"], ["11–14", "Rebellion and the forty years"], ["15–25", "Wandering"], ["26–36", "The new generation"]],
    keys: ["Numbers 6:24-26", "Numbers 14:24", "Numbers 23:19"] },
  deuteronomy: { wrote: "Moses, by long-standing tradition", when: "about 1400 BC", theme: "covenant renewed",
    summary: "On the plains of Moab, Moses preaches the law a second time to the generation about to cross the Jordan. He sets before them life and death, blessing and cursing, and calls them to love the LORD with all their heart.",
    outline: [["1–4", "Looking back"], ["5–26", "The law restated"], ["27–30", "Blessing and cursing"], ["31–34", "Moses' last words and death"]],
    keys: ["Deuteronomy 6:4-5", "Deuteronomy 30:19", "Deuteronomy 31:6"] },
  joshua: { wrote: "Joshua, by long-standing tradition", when: "about 1370 BC", theme: "taking the land",
    summary: "Joshua leads Israel across the Jordan and into Canaan, beginning at Jericho. The land is taken and divided among the tribes, and not one word of God's promise fails.",
    outline: [["1–5", "Crossing over"], ["6–12", "The campaigns"], ["13–21", "Dividing the land"], ["22–24", "Joshua's farewell"]],
    keys: ["Joshua 1:9", "Joshua 21:45", "Joshua 24:15"] },
  judges: { wrote: "Not named in the book; traditionally Samuel", when: "about 1050 BC", theme: "the cycle of sin and rescue",
    summary: "After Joshua's generation dies, Israel repeats a cycle: they forsake the LORD, they are oppressed, they cry out, and he raises up a judge to deliver them. The book ends in moral collapse, with every man doing what was right in his own eyes.",
    outline: [["1–2", "An unfinished conquest"], ["3–16", "The judges, from Othniel to Samson"], ["17–21", "Collapse"]],
    keys: ["Judges 2:16", "Judges 6:12", "Judges 21:25"] },
  ruth: { wrote: "Not named in the book; traditionally Samuel", when: "about 1000 BC", theme: "loyalty and redemption",
    summary: "In the days of the judges, a widow named Ruth leaves Moab to stay with her mother-in-law Naomi and her God. Boaz redeems her, and their great-grandson is David.",
    outline: [["1", "Loss and loyalty"], ["2", "Gleaning in the field of Boaz"], ["3", "The threshingfloor"], ["4", "Redeemed"]],
    keys: ["Ruth 1:16-17", "Ruth 2:12", "Ruth 4:17"] },
  "1-samuel": { wrote: "Not named; traditionally Samuel, Nathan, and Gad", when: "about 950 BC", theme: "Israel asks for a king",
    summary: "Samuel is given in answer to prayer and grows up to be prophet and judge. Israel demands a king, Saul is anointed and then rejected, and God sends Samuel to anoint David instead.",
    outline: [["1–7", "Samuel"], ["8–15", "Saul made king, and rejected"], ["16–31", "David and Saul"]],
    keys: ["1 Samuel 15:22", "1 Samuel 16:7", "1 Samuel 17:47"] },
  "2-samuel": { wrote: "Not named; traditionally Nathan and Gad", when: "about 950 BC", theme: "the reign of David",
    summary: "David is made king over all Israel, brings the ark to Jerusalem, and receives the promise of an everlasting throne. His sin with Bathsheba is forgiven, but its consequences run through the rest of his house.",
    outline: [["1–10", "David established"], ["11–12", "Sin and repentance"], ["13–20", "Trouble in his house"], ["21–24", "Final years"]],
    keys: ["2 Samuel 7:16", "2 Samuel 12:13", "2 Samuel 22:2"] },
  "1-kings": { wrote: "Not named; traditionally Jeremiah", when: "about 560 BC", theme: "the kingdom divides",
    summary: "Solomon asks for wisdom, builds the temple, and then turns away in his old age. The kingdom splits in two after him, and Elijah confronts Ahab and the prophets of Baal on Carmel.",
    outline: [["1–11", "Solomon"], ["12–16", "The kingdom divided"], ["17–22", "Elijah"]],
    keys: ["1 Kings 3:9", "1 Kings 8:27", "1 Kings 18:21"] },
  "2-kings": { wrote: "Not named; traditionally Jeremiah", when: "about 560 BC", theme: "decline and exile",
    summary: "Elisha carries on Elijah's ministry while both kingdoms slide toward judgment. Israel falls to Assyria and Judah to Babylon, exactly as the prophets had warned.",
    outline: [["1–8", "Elisha"], ["9–17", "Israel to the fall of Samaria"], ["18–25", "Judah to the fall of Jerusalem"]],
    keys: ["2 Kings 2:11", "2 Kings 6:16", "2 Kings 20:5"] },
  "1-chronicles": { wrote: "Not named; traditionally Ezra", when: "about 450 BC", theme: "David and worship",
    summary: "Chronicles retells Israel's history for the people who came home from exile, beginning with genealogies from Adam onward. Its account of David centres on the ark, the temple plans, and the ordering of worship.",
    outline: [["1–9", "Genealogies"], ["10–12", "David becomes king"], ["13–17", "The ark and the covenant"], ["18–29", "Preparing for the temple"]],
    keys: ["1 Chronicles 4:10", "1 Chronicles 16:11", "1 Chronicles 29:11"] },
  "2-chronicles": { wrote: "Not named; traditionally Ezra", when: "about 450 BC", theme: "the temple and revival",
    summary: "Solomon builds and dedicates the temple, and the book follows the kings of Judah from that height to the exile. Its bright spots are the revivals under Asa, Jehoshaphat, Hezekiah, and Josiah.",
    outline: [["1–9", "Solomon and the temple"], ["10–28", "The kings of Judah"], ["29–36", "Revival, then exile"]],
    keys: ["2 Chronicles 7:14", "2 Chronicles 16:9", "2 Chronicles 20:15"] },
  ezra: { wrote: "Ezra the scribe", when: "about 450 BC", theme: "coming home to rebuild",
    summary: "Cyrus sends the exiles home, and the altar and temple are rebuilt in the face of opposition. Ezra arrives later with a second company and sets himself to teach the law.",
    outline: [["1–6", "The temple rebuilt"], ["7–10", "Ezra and reform"]],
    keys: ["Ezra 3:11", "Ezra 7:10", "Ezra 8:22"] },
  nehemiah: { wrote: "Nehemiah", when: "about 430 BC", theme: "rebuilding the wall",
    summary: "Nehemiah hears that Jerusalem lies in ruins, prays, and asks the king to send him. The wall is finished in fifty-two days despite threats and discouragement, and the people gather to hear the law read.",
    outline: [["1–2", "Prayer and permission"], ["3–7", "Building under opposition"], ["8–10", "The law and the covenant"], ["11–13", "Settling the city"]],
    keys: ["Nehemiah 4:6", "Nehemiah 6:3", "Nehemiah 8:10"] },
  esther: { wrote: "Not named in the book", when: "about 460 BC", theme: "unseen providence",
    summary: "A Jewish orphan becomes queen of Persia, and her people are marked for destruction by Haman's plot. God is never named in Esther, but his hand is on every turn of it.",
    outline: [["1–2", "Esther becomes queen"], ["3–5", "Haman's plot"], ["6–7", "The tables turned"], ["8–10", "Deliverance and Purim"]],
    keys: ["Esther 4:14", "Esther 4:16", "Esther 9:22"] },
  job: { wrote: "Not named; among the oldest books of the Bible", when: "date unknown", theme: "suffering and the sovereignty of God",
    summary: "Job loses his children, his wealth, and his health, and his friends insist he must have earned it. God finally answers, not with explanations but with himself, and Job is satisfied.",
    outline: [["1–2", "The test"], ["3–31", "Job and his three friends"], ["32–37", "Elihu"], ["38–41", "God answers"], ["42", "Restored"]],
    keys: ["Job 1:21", "Job 19:25", "Job 42:2"] },
  psalms: { wrote: "David and others, including Asaph, the sons of Korah, and Moses", when: "about 1400–450 BC", theme: "prayer and praise",
    summary: "The Psalms are Israel's prayer book and hymn book — lament, thanksgiving, confession, and praise, arranged in five books. They give words to almost everything a believer can feel.",
    outline: [["1–41", "Book I"], ["42–72", "Book II"], ["73–89", "Book III"], ["90–106", "Book IV"], ["107–150", "Book V"]],
    keys: ["Psalm 23:1", "Psalm 46:1", "Psalm 119:105"] },
  proverbs: { wrote: "Solomon, with sayings of Agur and Lemuel", when: "about 950 BC", theme: "wisdom for daily life",
    summary: "Proverbs is practical wisdom for ordinary days — money, words, work, friendship, temper, and the company you keep. It begins where wisdom begins, with the fear of the LORD.",
    outline: [["1–9", "Wisdom's call"], ["10–24", "The proverbs of Solomon"], ["25–29", "Copied out by Hezekiah's men"], ["30–31", "Agur, Lemuel, and the virtuous woman"]],
    keys: ["Proverbs 1:7", "Proverbs 3:5-6", "Proverbs 22:6"] },
  ecclesiastes: { wrote: "The Preacher, traditionally Solomon", when: "about 930 BC", theme: "life under the sun",
    summary: "The Preacher tries pleasure, work, wealth, and wisdom, and finds every one of them empty when pursued for its own sake. His conclusion is to fear God and keep his commandments.",
    outline: [["1–2", "All is vanity"], ["3–6", "Times and seasons"], ["7–11", "Wisdom and folly"], ["12", "The whole duty of man"]],
    keys: ["Ecclesiastes 1:2", "Ecclesiastes 3:1", "Ecclesiastes 12:13"] },
  "song-of-solomon": { wrote: "Solomon", when: "about 950 BC", theme: "love and marriage",
    summary: "A love song between a bride and her beloved, unembarrassed about affection and faithfulness. Many readers have also seen in it a picture of Christ's love for his people.",
    outline: [["1–3", "Courtship"], ["4–5", "The wedding"], ["6–8", "Love matured"]],
    keys: ["Song of Solomon 2:16", "Song of Solomon 4:7", "Song of Solomon 8:7"] },
  isaiah: { wrote: "Isaiah the son of Amoz", when: "about 700 BC", theme: "judgment and comfort",
    summary: "Isaiah warns Judah of judgment, then turns to comfort with some of the clearest promises of a coming Saviour in the Old Testament. Chapter 53 describes a servant wounded for our transgressions.",
    outline: [["1–39", "Judgment"], ["40–55", "Comfort and the servant"], ["56–66", "Glory to come"]],
    keys: ["Isaiah 9:6", "Isaiah 40:31", "Isaiah 53:5"] },
  jeremiah: { wrote: "Jeremiah, written down with Baruch", when: "about 580 BC", theme: "warning before the exile",
    summary: "Called as a young man, Jeremiah preaches for forty years to a nation that will not listen, and watches Jerusalem fall. Within the warnings is the promise of a new covenant written on the heart.",
    outline: [["1", "The call"], ["2–29", "Warnings to Judah"], ["30–33", "The new covenant"], ["34–52", "The fall of Jerusalem"]],
    keys: ["Jeremiah 1:5", "Jeremiah 29:11", "Jeremiah 31:3"] },
  lamentations: { wrote: "Not named; traditionally Jeremiah", when: "about 586 BC", theme: "grief and mercy",
    summary: "Five poems of grief over the ruin of Jerusalem, written by someone who saw it. At the lowest point comes the line about mercies that are new every morning.",
    outline: [["1–2", "The city desolate"], ["3", "Hope in the midst of grief"], ["4–5", "Affliction and a plea"]],
    keys: ["Lamentations 3:22-23", "Lamentations 3:25-26", "Lamentations 5:21"] },
  ezekiel: { wrote: "Ezekiel the priest", when: "about 570 BC", theme: "visions in exile",
    summary: "Ezekiel prophesies to the exiles in Babylon in visions and signs — the glory of God, the watchman, the valley of dry bones. God promises to take away the stony heart and give a heart of flesh.",
    outline: [["1–24", "Judgment on Jerusalem"], ["25–32", "The nations"], ["33–39", "Restoration and dry bones"], ["40–48", "The temple vision"]],
    keys: ["Ezekiel 22:30", "Ezekiel 36:26", "Ezekiel 37:5"] },
  daniel: { wrote: "Daniel", when: "about 530 BC", theme: "faithfulness and prophecy",
    summary: "Taken captive as a youth, Daniel purposes not to defile himself and serves under four kings without bending. Alongside the lions' den and the fiery furnace are visions of kingdoms rising and falling until God's kingdom stands forever.",
    outline: [["1–6", "Faithful in Babylon"], ["7–9", "Visions of kingdoms"], ["10–12", "The last vision"]],
    keys: ["Daniel 1:8", "Daniel 3:17-18", "Daniel 12:3"] },
  hosea: { wrote: "Hosea", when: "about 750 BC", theme: "covenant love",
    summary: "Hosea is told to marry a wife who will be unfaithful, and his marriage becomes a picture of God and Israel. The book alternates between grief over sin and a love that will not let go.",
    outline: [["1–3", "Hosea and Gomer"], ["4–13", "Israel's unfaithfulness"], ["14", "Return and be healed"]],
    keys: ["Hosea 6:3", "Hosea 6:6", "Hosea 14:4"] },
  joel: { wrote: "Joel the son of Pethuel", when: "date uncertain", theme: "the day of the LORD",
    summary: "A locust plague becomes the occasion to call a nation to repentance. Joel promises restored years and the Spirit poured out on all flesh — the passage Peter quoted at Pentecost.",
    outline: [["1", "The locusts"], ["2", "Rend your heart"], ["3", "The nations judged"]],
    keys: ["Joel 2:13", "Joel 2:25", "Joel 2:28"] },
  amos: { wrote: "Amos, a herdman of Tekoa", when: "about 760 BC", theme: "justice",
    summary: "A farmer from Judah is sent north to a prosperous, complacent Israel. Amos condemns religion without righteousness and calls for justice to run down like water.",
    outline: [["1–2", "Judgment on the nations, and on Israel"], ["3–6", "Three sermons"], ["7–9", "Five visions, and restoration"]],
    keys: ["Amos 3:7", "Amos 5:14", "Amos 5:24"] },
  obadiah: { wrote: "Obadiah", when: "date uncertain", theme: "pride brought down",
    summary: "The shortest book in the Old Testament, one chapter against Edom for standing by while Jerusalem was plundered. The pride of the heart deceives those who think themselves unreachable.",
    outline: [["1–14", "Edom's pride and violence"], ["15–21", "The day of the LORD"]],
    keys: ["Obadiah 1:3", "Obadiah 1:15", "Obadiah 1:21"] },
  jonah: { wrote: "Not named; traditionally Jonah", when: "about 760 BC", theme: "mercy on a city",
    summary: "Jonah runs from a commission to preach to Nineveh and is brought back by a storm and a great fish. Nineveh repents, and Jonah is angry that God spared it.",
    outline: [["1", "Running"], ["2", "Praying"], ["3", "Preaching"], ["4", "Pouting"]],
    keys: ["Jonah 2:9", "Jonah 3:10", "Jonah 4:2"] },
  micah: { wrote: "Micah the Morasthite", when: "about 700 BC", theme: "justice, mercy, humility",
    summary: "Micah preaches against the leaders, priests, and prophets who use their office for gain. He names Bethlehem as the birthplace of the ruler in Israel, and sums up what God requires in a single verse.",
    outline: [["1–3", "Judgment"], ["4–5", "The kingdom and Bethlehem"], ["6–7", "What doth the LORD require"]],
    keys: ["Micah 5:2", "Micah 6:8", "Micah 7:18"] },
  nahum: { wrote: "Nahum the Elkoshite", when: "about 650 BC", theme: "a stronghold in trouble",
    summary: "A century after Jonah, Nahum announces the fall of Nineveh. The same God who is slow to anger is a stronghold to those who trust him and will not acquit the wicked.",
    outline: [["1", "The character of God"], ["2", "The siege"], ["3", "Woe to the bloody city"]],
    keys: ["Nahum 1:3", "Nahum 1:7", "Nahum 1:15"] },
  habakkuk: { wrote: "Habakkuk", when: "about 610 BC", theme: "living by faith",
    summary: "Habakkuk asks God why he tolerates violence, and is told the answer will be worse than the question — Babylon is coming. He ends by resolving to rejoice in the LORD even if the fig tree does not blossom.",
    outline: [["1", "Two complaints"], ["2", "The just shall live by his faith"], ["3", "A prayer and a song"]],
    keys: ["Habakkuk 2:4", "Habakkuk 3:17-18", "Habakkuk 3:19"] },
  zephaniah: { wrote: "Zephaniah", when: "about 630 BC", theme: "the day of the LORD",
    summary: "Zephaniah warns of a day of wrath on Judah and the nations, and calls the meek to seek the LORD. It closes with God rejoicing over his people with singing.",
    outline: [["1", "The day of the LORD"], ["2", "Seek ye the LORD"], ["3", "Judgment and joy"]],
    keys: ["Zephaniah 2:3", "Zephaniah 3:9", "Zephaniah 3:17"] },
  haggai: { wrote: "Haggai", when: "about 520 BC", theme: "consider your ways",
    summary: "The returned exiles have panelled their own houses while the temple lies waste. In four short messages Haggai stirs them to build, and they begin within a month.",
    outline: [["1", "Consider your ways"], ["2", "Be strong, and work"]],
    keys: ["Haggai 1:5", "Haggai 2:4", "Haggai 2:9"] },
  zechariah: { wrote: "Zechariah the son of Berechiah", when: "about 520 BC", theme: "restoration and the coming King",
    summary: "Zechariah encourages the temple builders with eight night visions and the word that it is not by might nor by power, but by God's Spirit. Later chapters look ahead to a King coming lowly, riding upon an ass.",
    outline: [["1–6", "Eight visions"], ["7–8", "Questions about fasting"], ["9–14", "The coming King"]],
    keys: ["Zechariah 4:6", "Zechariah 9:9", "Zechariah 14:9"] },
  malachi: { wrote: "Malachi", when: "about 430 BC", theme: "the last word before the silence",
    summary: "Malachi answers a people who have grown cynical about worship, tithing, and marriage, in a series of questions and replies. It ends the Old Testament looking forward to a messenger who will prepare the way.",
    outline: [["1–2", "Careless worship and broken faith"], ["3", "Bring ye all the tithes"], ["4", "The day that cometh"]],
    keys: ["Malachi 3:6", "Malachi 3:10", "Malachi 4:2"] },
  matthew: { wrote: "Matthew, also called Levi, one of the twelve", when: "about AD 60", theme: "Jesus the promised King",
    summary: "Matthew writes for readers who know the Old Testament, showing again and again that Jesus is the King the prophets promised. It holds the Sermon on the Mount and closes with the Great Commission.",
    outline: [["1–4", "Birth and beginnings"], ["5–7", "The Sermon on the Mount"], ["8–20", "Ministry in Galilee"], ["21–25", "The last week's teaching"], ["26–28", "The cross and the resurrection"]],
    keys: ["Matthew 6:33", "Matthew 11:28", "Matthew 28:19-20"] },
  mark: { wrote: "John Mark, drawing on Peter's account", when: "about AD 55", theme: "Jesus the servant",
    summary: "The shortest Gospel, and the fastest — Mark moves from one event to the next with the word straightway. He presents Jesus as the servant who came not to be ministered unto, but to minister.",
    outline: [["1–8", "Ministry in Galilee"], ["9–10", "Toward Jerusalem"], ["11–13", "The last week"], ["14–16", "The cross and the resurrection"]],
    keys: ["Mark 10:45", "Mark 12:30-31", "Mark 16:15"] },
  luke: { wrote: "Luke the physician, Paul's companion", when: "about AD 60", theme: "Jesus the Son of man",
    summary: "Luke investigates everything from the first and sets it in order for Theophilus, giving the fullest account of the birth of Christ. He has a particular eye for the poor, for women, and for outsiders.",
    outline: [["1–2", "The birth of Christ"], ["3–9", "Ministry in Galilee"], ["10–19", "The journey to Jerusalem"], ["20–24", "The cross and the resurrection"]],
    keys: ["Luke 1:37", "Luke 2:11", "Luke 19:10"] },
  john: { wrote: "John, the disciple whom Jesus loved", when: "about AD 90", theme: "believe and have life",
    summary: "John selects seven signs and a series of I AM sayings, and states his purpose plainly: that you might believe that Jesus is the Christ, and that believing you might have life through his name. It is the Gospel most often handed to a new reader.",
    outline: [["1–12", "The signs and the public ministry"], ["13–17", "The upper room"], ["18–19", "The cross"], ["20–21", "The resurrection"]],
    keys: ["John 1:1", "John 3:16", "John 14:6"] },
  acts: { wrote: "Luke", when: "about AD 63", theme: "the church begins",
    summary: "Acts picks up where Luke's Gospel ends and follows the gospel from Jerusalem to Rome, carried by ordinary people filled with the Spirit. The first half centres on Peter, the second on Paul.",
    outline: [["1–7", "Jerusalem"], ["8–12", "Judaea and Samaria"], ["13–20", "Paul's journeys"], ["21–28", "Arrest, defence, and Rome"]],
    keys: ["Acts 1:8", "Acts 2:38", "Acts 4:12"] },
  romans: { wrote: "Paul", when: "about AD 57", theme: "the gospel explained",
    summary: "Paul's fullest statement of the gospel: all have sinned, justification is by faith, and nothing can separate believers from the love of God. The last chapters turn doctrine into daily life.",
    outline: [["1–3", "All under sin"], ["4–5", "Justified by faith"], ["6–8", "Life in the Spirit"], ["9–11", "Israel"], ["12–16", "Living it out"]],
    keys: ["Romans 3:23", "Romans 6:23", "Romans 8:28"] },
  "1-corinthians": { wrote: "Paul", when: "about AD 55", theme: "correcting a divided church",
    summary: "Paul writes to a gifted, quarrelsome church about division, immorality, lawsuits, marriage, the Lord's supper, and spiritual gifts. In the middle of the corrections stands the chapter on charity, and at the end the resurrection.",
    outline: [["1–4", "Divisions"], ["5–10", "Disorder and liberty"], ["11–14", "Worship and gifts"], ["15–16", "The resurrection"]],
    keys: ["1 Corinthians 10:13", "1 Corinthians 13:4-7", "1 Corinthians 15:57"] },
  "2-corinthians": { wrote: "Paul", when: "about AD 56", theme: "strength in weakness",
    summary: "The most personal of Paul's letters, written after a painful visit, defending his ministry and describing the comfort of God in affliction. It is where grace is said to be sufficient, and strength made perfect in weakness.",
    outline: [["1–7", "Paul's ministry"], ["8–9", "The collection for the saints"], ["10–13", "Defending his apostleship"]],
    keys: ["2 Corinthians 1:3-4", "2 Corinthians 5:17", "2 Corinthians 12:9"] },
  galatians: { wrote: "Paul", when: "about AD 49", theme: "freedom in Christ",
    summary: "Churches in Galatia were being told that faith in Christ was not enough without the law. Paul answers sharply: a man is justified by faith, and the liberty Christ gives is not to be traded away.",
    outline: [["1–2", "Paul's gospel defended"], ["3–4", "Faith, not law"], ["5–6", "Walk in the Spirit"]],
    keys: ["Galatians 2:20", "Galatians 5:1", "Galatians 5:22-23"] },
  ephesians: { wrote: "Paul, writing from prison", when: "about AD 62", theme: "riches in Christ",
    summary: "The first half describes what believers have in Christ; the second half describes how to walk worthy of it, at home and at work. It closes with the armour of God.",
    outline: [["1–3", "What we have in Christ"], ["4–6", "How then to walk"], ["6", "The whole armour of God"]],
    keys: ["Ephesians 2:8-9", "Ephesians 4:32", "Ephesians 6:10-11"] },
  philippians: { wrote: "Paul, writing from prison", when: "about AD 62", theme: "joy in any circumstance",
    summary: "A thank-you letter to the church that supported him, written in chains and full of joy. Paul says he has learned to be content in whatever state he is in.",
    outline: [["1", "To live is Christ"], ["2", "The mind of Christ"], ["3", "Pressing toward the mark"], ["4", "Contentment and peace"]],
    keys: ["Philippians 1:6", "Philippians 4:6-7", "Philippians 4:13"] },
  colossians: { wrote: "Paul, writing from prison", when: "about AD 62", theme: "the supremacy of Christ",
    summary: "Against teaching that added philosophy and ritual to Christ, Paul answers that in him all fulness dwells and by him all things consist. What follows is how that works out in the home and in ordinary work.",
    outline: [["1", "Christ preeminent"], ["2", "Complete in him"], ["3–4", "The new man at home and at work"]],
    keys: ["Colossians 1:16-17", "Colossians 3:2", "Colossians 3:23"] },
  "1-thessalonians": { wrote: "Paul", when: "about AD 51", theme: "waiting for his return",
    summary: "One of Paul's earliest letters, written to a young church under pressure. Every chapter ends looking toward the coming of the Lord, including the clearest description of the resurrection of believers.",
    outline: [["1–3", "Thanksgiving and memories"], ["4", "Holiness and the Lord's coming"], ["5", "Ready and awake"]],
    keys: ["1 Thessalonians 4:16-17", "1 Thessalonians 5:11", "1 Thessalonians 5:16-18"] },
  "2-thessalonians": { wrote: "Paul", when: "about AD 51", theme: "steadfastness",
    summary: "A follow-up letter correcting the idea that the day of Christ had already come, and the idleness that had followed it. Paul tells them to stand fast, and that if any would not work, neither should he eat.",
    outline: [["1", "Comfort under persecution"], ["2", "The day of Christ"], ["3", "Work and stand fast"]],
    keys: ["2 Thessalonians 3:3", "2 Thessalonians 3:10", "2 Thessalonians 3:16"] },
  "1-timothy": { wrote: "Paul", when: "about AD 63", theme: "order in the church",
    summary: "Paul writes to a young pastor at Ephesus about sound doctrine, prayer, the qualifications of church leaders, and the care of widows. He tells him to let no man despise his youth.",
    outline: [["1", "Charge against false teaching"], ["2–3", "Prayer and leadership"], ["4–6", "A good minister of Jesus Christ"]],
    keys: ["1 Timothy 2:5", "1 Timothy 4:12", "1 Timothy 6:12"] },
  "2-timothy": { wrote: "Paul, his last letter", when: "about AD 67", theme: "finish the course",
    summary: "Written from prison not long before his death, this is Paul's last word to Timothy: stir up the gift, endure hardness, preach the word. He says he has fought a good fight and finished his course.",
    outline: [["1", "Stir up the gift"], ["2", "Endure hardness"], ["3", "All scripture is given by inspiration"], ["4", "Preach the word"]],
    keys: ["2 Timothy 1:7", "2 Timothy 3:16", "2 Timothy 4:7"] },
  titus: { wrote: "Paul", when: "about AD 63", theme: "sound doctrine and good works",
    summary: "Titus is left in Crete to set things in order and ordain elders in every city. The letter ties what we believe to how we live, in every age group in the church.",
    outline: [["1", "Elders and false teachers"], ["2", "Teaching every age"], ["3", "Saved by mercy, careful to maintain good works"]],
    keys: ["Titus 2:11-12", "Titus 2:14", "Titus 3:5"] },
  philemon: { wrote: "Paul, writing from prison", when: "about AD 62", theme: "forgiveness",
    summary: "A private letter asking a Christian master to receive back a runaway slave, Onesimus, now converted. Paul offers to pay whatever he owes, and asks Philemon to receive him as a brother.",
    outline: [["1–7", "Thanksgiving for Philemon"], ["8–21", "The appeal for Onesimus"], ["22–25", "Closing"]],
    keys: ["Philemon 1:6", "Philemon 1:16", "Philemon 1:18"] },
  hebrews: { wrote: "Not named in the book; the author is unknown", when: "about AD 65", theme: "Christ is better",
    summary: "Written to Jewish believers tempted to go back, Hebrews shows Christ as better than the angels, Moses, the priesthood, and the sacrifices. Chapter 11 is the roll call of faith, and chapter 12 the call to run with patience.",
    outline: [["1–7", "A better person and priesthood"], ["8–10", "A better covenant and sacrifice"], ["11", "Faith"], ["12–13", "Run with patience"]],
    keys: ["Hebrews 4:12", "Hebrews 11:1", "Hebrews 12:1-2"] },
  james: { wrote: "James, the Lord's brother", when: "about AD 48", theme: "faith that works",
    summary: "The most practical letter in the New Testament — trials, the tongue, favouritism, money, patience, and prayer. James insists that faith without works is dead.",
    outline: [["1", "Trials and doers of the word"], ["2", "Faith and works"], ["3", "The tongue"], ["4–5", "Humility, patience, and prayer"]],
    keys: ["James 1:2-3", "James 1:5", "James 2:17"] },
  "1-peter": { wrote: "Peter", when: "about AD 64", theme: "hope under suffering",
    summary: "Peter writes to scattered believers facing hostility, calling them a chosen generation and a royal priesthood. He tells them to cast all their care upon God, because he careth for them.",
    outline: [["1", "A living hope"], ["2–3", "Submission and a good conscience"], ["4–5", "Suffering and shepherding"]],
    keys: ["1 Peter 2:9", "1 Peter 3:15", "1 Peter 5:7"] },
  "2-peter": { wrote: "Peter, near the end of his life", when: "about AD 66", theme: "grow, and beware",
    summary: "Peter urges believers to add to their faith and warns at length about false teachers who deny the Lord. He answers scoffers who ask where the promise of his coming is: God is not slack, but longsuffering.",
    outline: [["1", "Add to your faith"], ["2", "False teachers"], ["3", "The day of the Lord"]],
    keys: ["2 Peter 1:3", "2 Peter 3:9", "2 Peter 3:18"] },
  "1-john": { wrote: "John the apostle", when: "about AD 90", theme: "assurance",
    summary: "John writes so that believers may know that they have eternal life, testing it three ways: walking in the light, loving the brethren, and believing that Jesus is the Christ. It is where confession meets a promise of cleansing.",
    outline: [["1–2", "Walking in the light"], ["3–4", "Love one another"], ["5", "That ye may know"]],
    keys: ["1 John 1:9", "1 John 4:19", "1 John 5:13"] },
  "2-john": { wrote: "John, writing as the elder", when: "about AD 90", theme: "truth and love together",
    summary: "A short letter to an elect lady and her children, joining two things that are often separated: walking in truth and walking in love. It warns about receiving those who bring another doctrine.",
    outline: [["1–6", "Walk in truth and love"], ["7–13", "Beware of deceivers"]],
    keys: ["2 John 1:4", "2 John 1:6", "2 John 1:9"] },
  "3-john": { wrote: "John, writing as the elder", when: "about AD 90", theme: "hospitality",
    summary: "John commends Gaius for receiving travelling preachers and rebukes Diotrephes, who loved to have the preeminence. His joy is to hear that his children walk in truth.",
    outline: [["1–8", "Gaius the hospitable"], ["9–14", "Diotrephes and Demetrius"]],
    keys: ["3 John 1:2", "3 John 1:4", "3 John 1:11"] },
  jude: { wrote: "Jude, the brother of James", when: "about AD 65", theme: "contend for the faith",
    summary: "Jude set out to write about the common salvation and wrote instead an urgent warning about men who crept in unawares. It ends with one of the great benedictions in scripture.",
    outline: [["1–4", "Contend earnestly"], ["5–16", "Examples and warnings"], ["17–25", "Build yourselves up"]],
    keys: ["Jude 1:3", "Jude 1:20-21", "Jude 1:24-25"] },
  revelation: { wrote: "John, exiled on the isle of Patmos", when: "about AD 95", theme: "the unveiling of Christ",
    summary: "Revelation opens with letters to seven churches and moves into visions of judgment, the return of Christ, and a new heaven and a new earth. It ends with God wiping away all tears, and an invitation to whosoever will.",
    outline: [["1–3", "Letters to the seven churches"], ["4–18", "The throne and the judgments"], ["19–20", "The return of Christ"], ["21–22", "A new heaven and a new earth"]],
    keys: ["Revelation 3:20", "Revelation 21:4", "Revelation 22:13"] },
};
