/**
 * seo/meanings.js — plain-language "what this verse means" paragraphs, written
 * for TheWay and approved by Dillon. Everything else on a verse page (the KJV
 * text, the cross references, the Matthew Henry excerpt) is public domain and
 * sits on every competing Bible site; this is the only writing here that is
 * ours, and it is what an AI assistant quotes when somebody asks what a verse
 * means.
 *
 * Keyed by reference exactly as refLabel() prints it (so "Psalm 23:1", not
 * "Psalms 23:1"). Anything that does not resolve through parseRef is ignored,
 * and a verse with no entry simply renders without the section.
 *
 * Batch 1: the 25 best-known verses.
 * Batch 2: queries Search Console showed the site already ranking for, plus
 *          the next tier of high-volume verses.
 * Batch 3 (Sept 19): picked straight off the Search Console query report
 *          sorted by impressions — pages already being shown to searchers at
 *          about position 47 with no clicks, e.g. Isaiah 54:17 (40
 *          impressions), Romans 15:13 (37), Matthew 17:1-8 (36), Ephesians
 *          6:12 (28, plus 25 more for "we wrestle not against flesh and
 *          blood"). Impressions without clicks means Google is offering the
 *          page and nobody is choosing it; a real explanation is the fix.
 *
 * Keep the register plain and spoken, and run the voice-check skill on every
 * new batch before it ships.
 * Batch 4 (Sept 19): the next tier of high-volume verses not yet covered —
 *          comfort, calling and decision passages people search by phrase.
 */
export const VERSE_MEANINGS = {
  "John 3:16": "Jesus says this at night, to a religious leader who came with questions. The love is God's, the giving costs him his Son, and the offer is open to whosoever — not to a short list of people who had it together. Believing here isn't agreeing that it happened. It's trusting him with where you end up.",
  "Jeremiah 29:11": "God wrote this to people already in Babylon who weren't going home for seventy years. In the same letter he tells them to build houses and plant gardens right where they are. So the promise isn't that you'll be spared the hard years. It's that God is still thinking toward you in the middle of them.",
  "Philippians 4:13": "Paul wrote this from a jail cell, in a paragraph about learning to be content. He'd been full and he'd been hungry, and he says he learned it in both. The verse isn't a promise that you'll win. It's a promise that Christ will hold you steady either way.",
  "Romans 8:28": "It doesn't say all things are good. It says God works them together for good, which is a different claim and a harder one. Paul had just been writing about groaning and weakness, so he isn't pretending the loss is small. The comfort is that God is still working while you wait.",
  "Psalm 23:1": "David kept sheep before he was king, so he knew what he was claiming. A shepherd means the sheep doesn't have to find its own food, water, or way home. I shall not want isn't a promise of everything you'd like. It's the settled sense that nothing you actually need is missing.",
  "Proverbs 3:5-6": "Leaning is what you do when you're tired — you put your weight on something. Solomon isn't saying your understanding is worthless, he's saying it's too small to hold you up. And acknowledge him in all thy ways takes in the ordinary decisions, not just the ones that feel big.",
  "Isaiah 41:10": "God says this to people staring at an army they can't beat. Look at how much of it is what he will do: strengthen, help, uphold. The command not to fear comes with a reason attached, and the reason is him, not you.",
  "Joshua 1:9": "Moses had just died and Joshua had to take a nation into a fight. God says be strong and of a good courage three times in this one chapter, which tells you Joshua needed to hear it more than once. The courage isn't something he worked up. It rests on the last line: the LORD thy God is with thee whithersoever thou goest.",
  "Matthew 11:28": "Jesus said this to people worn out by religion that kept adding to the pile. Come unto me is an invitation, not a requirement to clean yourself up first. And the rest he offers isn't a day off. It's rest for the soul, which is the part that doesn't get better with sleep.",
  "Romans 12:2": "Conformed is pressure from the outside. Transformed is change that starts inside and works out. Paul says it happens by the renewing of your mind, which is slower than a decision and lasts longer. You come to know God's will by becoming the kind of person who can recognize it.",
  "Philippians 4:6-7": "The opposite of being careful for nothing isn't feeling calm. It's praying about the thing instead of carrying it. Paul puts thanksgiving in the same breath, before anything has changed. And what's promised isn't the answer you asked for — it's a peace that keeps guard over you while you wait for one.",
  "1 Corinthians 13:4-7": "Paul wrote this to a church that was fighting, not to a wedding. Read the list as things love does rather than things it feels: suffereth long, is kind, is not easily provoked. It's the plainest test in the Bible for whether love is real. Put your own name where the word charity is and read it again.",
  "Galatians 5:22-23": "Fruit is singular here — one fruit, nine parts to it. Fruit grows, which is Paul's whole argument against trying to manufacture godliness by effort. You don't get to pick the three you like. They come in together, from the same Spirit.",
  "Ephesians 2:8-9": "Grace is the reason, faith is how you receive it, and Paul says the whole thing is the gift of God, not of yourselves. If you could earn it you'd have something to boast about, and he shuts that door. The next verse says we're created unto good works — so works still matter, just never as the price.",
  "Isaiah 40:31": "The promise is made to people who are tired, not to people who are strong. Waiting on the LORD isn't standing still; it's the kind of waiting that keeps expecting him to act. And watch the order — mount up, run, walk. Walking without fainting is the hardest of the three, and it comes last for a reason.",
  "Psalm 46:1": "A very present help means help that's already here, not help that's coming. The psalm goes straight on to picture mountains falling into the sea, the worst thing the writer could imagine. Refuge is where you go. Strength is what you're handed when you get there.",
  "2 Timothy 1:7": "Paul wrote this to a young pastor with real reason to be afraid. Notice fear isn't called a weakness to push through — it's named as something God didn't give. What he did give comes in three parts: power to act, love so you don't go hard, and a sound mind to think straight when you're scared.",
  "Hebrews 11:1": "This is the Bible's own definition of faith, and it isn't wishful thinking. Substance and evidence are solid words — they describe something that's actually there. Faith isn't believing without a reason. It's acting on what God said before you can see how it turns out.",
  "Romans 6:23": "Wages are earned. A gift isn't. Paul sets the two side by side so you can see that everybody receives one or the other, and nobody gets both. Death is what sin pays out. Eternal life is handed to people who never worked a day for it.",
  "Romans 10:9": "Two things are named here: the mouth and the heart, said out loud and believed inside. The confession is that Jesus is Lord, which is a surrender before it's a sentence. And Paul ties it to the resurrection, because a Christ who stayed in the grave saves nobody.",
  "John 14:6": "Thomas had just admitted he didn't know where Jesus was going or how to get there. Jesus doesn't answer with directions. He answers with himself — the way, the truth, and the life — and then says the line that still offends: no man cometh unto the Father, but by me.",
  "Matthew 6:33": "This lands at the end of a paragraph about food and clothes, spoken to people who didn't know whether they'd have either. Seek first is about order, not about ignoring the bills. Jesus says the things you're chasing get added when the kingdom goes at the front of the line.",
  "1 John 1:9": "To confess is to say the same thing about it that God says, without softening it. The promise rests on his character rather than on how sorry you managed to feel: he is faithful and just to forgive. And cleansed from all unrighteousness covers the parts you didn't know to name.",
  "Psalm 119:105": "A lamp in that world lit the next step, not the whole road. That's the honest picture of guidance here — enough light for one step, not a map of the next ten years. You get more of it when you move.",
  "Genesis 1:1": "The first sentence of the Bible doesn't argue for God. It assumes him. Everything after it — the light, the sea, the animals, the man — rests on this one claim being true. If God made the beginning, nothing that comes after is outside his reach.",
  "Proverbs 4:25-27": "Three body parts in three verses: the eyes, the feet, and the path under them. Solomon's counsel is about attention before it's about morality, because you end up where you're looking. Ponder the path of thy feet means think about where this road comes out before you take another step down it.",
  "Isaiah 26:3": "Perfect peace is the word for peace said twice, the way you'd repeat something to make it stronger. The condition is a mind stayed on God, and stayed is a leaning word — it's what you do with your weight. The peace isn't promised to people who feel settled. It's promised to people who keep their thoughts fixed on him.",
  "John 15:7": "This sits in the middle of the vine and the branches, so the promise belongs to a branch that's still attached. If ye abide in me, and my words abide in you is two conditions, not throat-clearing. Ask what ye will comes after them, not instead of them.",
  "Mark 12:30-31": "A scribe asked which commandment was first and Jesus gave him two. The first takes in heart, soul, mind and strength — every part of a person, with nothing held back. The second is measured against something you already do well, which is loving yourself. He ends it flat: there is none other commandment greater than these.",
  "Proverbs 30:5": "Every word of God is pure — the picture behind that word is metal refined until nothing false is left in it. Then comes the practical half: he is a shield unto them that put their trust in him. The shield isn't the book sitting on a shelf. It's God himself, to people who actually trust him.",
  "Ecclesiastes 3:1-8": "Solomon lists fourteen pairs, and the hard ones are in there with the good — a time to kill, a time to break down, a time to lose. He isn't saying every season is pleasant. He's saying every season is appointed, which means the one you're in has an end.",
  "John 3:35": "This is John the Baptist talking, not Jesus, and he says it while his own crowd is leaving him for someone else. If the Father has already given all things into the Son's hand, then John has nothing to protect. It's the sentence just before he says he must increase, but I must decrease.",
  "Jeremiah 23:23-24": "God is answering prophets who were telling people whatever they wanted to hear. Am I a God at hand, and not a God afar off is a question with an edge on it — you can't get far enough away to work unobserved. Can any hide himself in secret places that I shall not see him. The comfort and the warning are the same fact.",
  "Psalm 46:10": "Be still gets read as quiet your heart, but this psalm is about war — the verse before has God breaking the bow and burning the chariot. The command is closer to stop fighting and see who he is. And it's said to the nations as much as it's said to you.",
  "Matthew 6:34": "Jesus doesn't say tomorrow has no trouble in it. He says it has its own, and it will still be there when you arrive. Dragging it into today doesn't get you ready for it, it just means you carry it twice. Sufficient unto the day is the evil thereof is honest about the day you're actually in.",
  "1 Peter 5:7": "Casting is a throwing word. You don't set care down gently, you get rid of it. The reason is in the back half of the verse — for he careth for you — and Peter wrote it to people under real persecution. He put it straight after a line about humility, because pride is what makes a man keep carrying things.",
  "Isaiah 53:5": "Written centuries before the cross, and every verb points away from us: wounded, bruised, chastised, and with his stripes we are healed. The transgressions and the iniquities are ours. The wounds are his. That trade is the whole verse.",
  "Psalm 37:4": "Delight comes first, and it changes what comes second. The promise isn't that God hands over whatever you happen to want right now. It's that a heart delighting in him begins to want different things — and then he gives you the desires of your heart, because by then they're his.",
  "John 16:33": "Jesus said this within hours of the arrest, to men who were about to scatter on him. He doesn't soften the first half: in the world ye shall have tribulation. The good cheer isn't because the trouble isn't coming. It's because he has already overcome the world it's coming from.",
  "Deuteronomy 31:6": "Moses is handing the nation over to Joshua, knowing he isn't going with them. The courage he calls for rests on a promise about God rather than a read on the odds: he will not fail thee, nor forsake thee. The writer of Hebrews quotes this same line to Christians centuries later, which tells you how far it reaches.",
  "Lamentations 3:22-23": "This sits in the middle of a book of grief, written by a man who watched his city burn. He isn't over it — a few verses earlier he says his strength and his hope are perished. New every morning is what he preaches to himself in the dark, and that's exactly why it carries weight.",
  "James 1:5": "The offer is wide open — if any of you lack wisdom. God giveth to all men liberally, and upbraideth not, which means he doesn't hold the asking against you or bring up the last time. The one condition comes in the next verse: ask in faith, nothing wavering.",
  "Romans 5:8": "The timing is the point. Not after we cleaned ourselves up, not once we were sorry enough: while we were yet sinners, Christ died for us. That's what commendeth means here — God putting his love out where nobody could mistake it for a reward.",
  "2 Corinthians 5:17": "A new creature isn't an improved one. Old things are passed away, behold, all things are become new is the language of starting over, not touching up. And in Christ is where it happens — outside of him the verse makes no promise at all.",
  "Ephesians 6:10-11": "Be strong in the Lord, and in the power of his might — the strength is borrowed before any armour goes on. Paul says the whole armour for a reason, since partial armour just leaves a gap. And the enemy named here is the wiles of the devil, which are schemes rather than brute force.",
  "Colossians 3:23": "Paul wrote this to slaves, which is worth sitting with before applying it to a job you chose. Whatsoever ye do takes in the work nobody notices and nobody thanks you for. Doing it heartily, as to the Lord changes who you're working for without changing the work.",
  "Psalm 27:1": "Three words for what God is: light, salvation, strength. David asks his own question twice — whom shall I fear, of whom shall I be afraid — and both times the answer is nobody, on account of who is with him. He wrote it while men were hunting him.",
  "Matthew 28:19-20": "The command is to make disciples; going, baptizing and teaching are how it gets done. Teaching them to observe all things is the half that gets left off — not only to know what he commanded but to do it. Then the promise covers the whole stretch of it: lo, I am with you alway, even unto the end of the world.",
  "1 Corinthians 10:13": "Three things are said here. What you're facing isn't unique, it's such as is common to man. God is faithful, and he won't let it run past what you can bear. And there is always a way to escape, which makes the honest question in the moment whether you're looking for it.",
  "Psalm 91:1-2": "The secret place is close quarters — you can't dwell there and keep your distance at the same time. Watch the order: the one who dwells is the one who abides under the shadow. And the second verse is the psalmist saying it out loud, which is a different thing from only believing it.",
  "Isaiah 54:17": "No weapon that is formed against thee shall prosper is said to Israel on the far side of judgment, not handed out as a charm against every hardship. The verse ends by calling it the heritage of the servants of the LORD, so it belongs to his people. And notice it doesn't say no weapon gets formed. It says the ones that get formed don't finally win.",
  "Romans 15:13": "Paul calls him the God of hope, which makes hope something handed to you rather than something you work up. Joy and peace come in believing — they arrive with the trusting, not before it. And the abounding is credited to the power of the Holy Ghost, so this isn't a matter of trying to feel more hopeful than you do.",
  "Matthew 17:1-8": "Peter, James and John watch Jesus change in front of them, his face shining like the sun. Peter's instinct is to build something and stay up there, and the Father's answer cuts across it: hear ye him. When the voice stops they lift their eyes and see no man, save Jesus only, which is the whole point of the scene.",
  "John 15:5": "A branch doesn't strain to produce grapes. It stays attached, and the fruit follows. Without me ye can do nothing is the half people skip, and it's the reason the verse gets quoted at all. Abiding isn't a burst of effort — it's staying put.",
  "Galatians 2:20": "Paul says the old life is already over: I am crucified with Christ. What's living now is Christ in him, which is a change of occupant rather than self-improvement. And the life he still lives in the flesh he lives by the faith of the Son of God, who loved me, and gave himself for me.",
  "Romans 3:23": "All have sinned puts everybody on the same footing, which is exactly the argument Paul is making in this chapter. Come short of the glory of God is an archery picture — the arrow falls short of the mark, whether by an inch or a mile. That's why the next verse, about being justified freely by his grace, has to follow it.",
  "Ephesians 6:12": "We wrestle not against flesh and blood names the mistake first: the person in front of you isn't the real opponent. Paul lists principalities, powers, rulers of the darkness of this world, spiritual wickedness in high places. And wrestling is close work, not long range, which is why the armour that follows is for standing rather than charging.",
  "Galatians 6:9": "Be not weary in well doing assumes you will get weary, or Paul wouldn't have to say it. The harvest is promised in due season, which is God's timing and not yours. The whole thing hangs on the last clause: if we faint not.",
  "Philippians 1:6": "He which hath begun a good work in you will perform it — the confidence is in the one who started it, not in the one it's happening to. Paul puts the finish line at the day of Jesus Christ, so it was never going to be done this year. Begun and will finish are both his verbs.",
  "James 1:2-4": "Count it all joy is an accounting word. You decide what goes in the column, which is a different thing from feeling cheerful about it. James says the trying of your faith worketh patience, and that patience has to have her perfect work. The joy isn't about the trial, it's about what the trial is making.",
  "Romans 8:31": "If God be for us, who can be against us isn't a claim that nobody opposes you. Plenty opposed Paul and he knew their names. The question is about weight, not headcount — who can stand against the one who is for you. And it lands right after a list of what God has already done.",
  "Romans 8:18": "Paul isn't making light of the suffering. This is a man who had been beaten, jailed and shipwrecked. He's weighing it — I reckon is deliberate arithmetic — and his conclusion is that what's coming is so much heavier that the present sufferings don't tip the scale.",
  "Psalm 147:3": "He healeth the broken in heart, and bindeth up their wounds. Binding up is slow work, bandage rather than miracle. And it sits in the same breath as God counting the stars and calling them all by name, so the one who numbers the stars is the one doing the bandaging.",
  "Isaiah 43:2": "When thou passest through the waters — not if. God doesn't promise a way around the river or the fire. He promises to be in them with you, and that they shall not overflow thee and shall not kindle upon thee. Passing through also means there's another side to come out on.",
  "Psalm 118:6": "The LORD is on my side; I will not fear. The order matters: the fear goes because of who is with him, not because the threat left. What can man do unto me is a real question with a real answer — plenty, and none of it final.",
  "Proverbs 22:6": "Train up a child in the way he should go is written as a proverb, in a book full of them — how things generally run, not a contract with no exceptions. The way he should go can be read as God's way, or as the bent God gave that particular child. Either way, the training is the parent's part and the outcome is God's.",
  "1 Corinthians 13:4-8": "The same paragraph about love, carried one verse further, to charity never faileth. Paul is holding it up against the gifts the Corinthians prized most — prophecy, tongues, knowledge — and saying every one of those stops. Love doesn't. That's the argument the whole chapter is building toward.",
  "Psalm 62:4": "David is describing men who bless with their mouth, but they curse inwardly. It's a verse about two-faced dealing, and it's honest that this happens to people who are trying to do right. It sits inside a psalm that keeps circling back to God alone as the rock, which is the answer to it.",
  "Proverbs 1:30": "This is wisdom speaking about people who would none of my counsel, and despised all my reproof. The refusal is the whole point — it isn't that they never heard, it's that they decided. The verses around it name the cost: they eat the fruit of their own way.",
  "Deuteronomy 11:26-28": "Moses sets a blessing and a curse in front of the entire nation on the same day, and ties each one to obedience or to turning aside. It's plain language, and no third option is offered. The choice belonged to them, and he made sure they knew where each road came out.",
  "Psalm 23:4": "The valley of the shadow of death is a place you walk through, not a place you settle. Watch the psalm switch here from talking about God to talking to him — thou art with me. The rod and the staff are a shepherd's tools: one drives off what attacks, one pulls a wandering sheep back.",
  "John 1:1": "John opens where Genesis opens — in the beginning — and the Word is already there. Three claims stacked in one sentence: the Word was in the beginning, was with God, and was God. Verse fourteen tells you plainly who he has been talking about.",
  "Matthew 5:16": "Let your light so shine before men is not an instruction to get noticed. Watch where the sentence lands: that they may see your good works, and glorify your Father which is in heaven. The light is aimed past you on purpose.",
  "1 John 4:19": "We love him, because he first loved us. The order is the entire verse — his love starts it, ours answers it. John's argument through the chapter is that love isn't something we generate and hand up to God. It's something we received and pass along.",
  "Jeremiah 1:5": "God tells Jeremiah he knew him before he formed him in the belly and ordained him before he came out of the womb. This is said to a man who has just objected that he's too young for the work. The point isn't Jeremiah's qualifications — the call was there before he existed to have any.",
  "Psalm 121:1-2": "The hills aren't the help. The psalmist looks up at them and then answers his own question: my help cometh from the LORD, which made heaven and earth. This is a song for people on the road to Jerusalem, watching the high country where trouble usually came from. They looked past it.",
  "2 Chronicles 7:14": "God says this to Solomon about Israel, not about any nation since. Notice who is addressed: my people, which are called by my name. Four things are asked of them, and turning from their own wicked ways is the one that costs. The healing follows repentance, not a slogan.",
  "Micah 6:8": "Micah asks this right after listing sacrifices, thousands of rams and rivers of oil, as if a bigger offering could settle the account. The answer comes back smaller and harder. Do justly, love mercy, walk humbly. Two of the three are about how you treat people, and the third is about who you know you are.",
  "Matthew 7:7": "Three verbs, and each one takes more of you than the last. Asking is words, seeking is looking, knocking is standing at a door you can't open yourself. Jesus follows it with a father handing bread to his son, so the picture isn't a machine you operate. It's a family you belong to.",
  "Philippians 2:3-4": "Esteem other better than themselves isn't a low opinion of yourself. It's a habit of attention, counting somebody else's concerns as weighing more than yours today. Paul is settling a quarrel between two women in this church, and the next paragraph hands them Christ emptying himself as the pattern.",
  "Ephesians 4:32": "The measure is at the end: even as God for Christ's sake hath forgiven you. Paul just spent a paragraph on bitterness and anger, so he isn't talking about small slights. Forgiving here isn't deciding the wrong was minor. It's refusing to hold on to something God already let go of.",
  "Hebrews 12:1-2": "Two things get laid aside, and only one of them is sin. A weight can be harmless in itself and still slow you down. The race is run with patience rather than speed, and the runner's eyes are off the track entirely, looking unto Jesus, the author and finisher of our faith.",
  "Hebrews 13:8": "The verse sits between a word about leaders who have died and a warning about strange doctrines. That's the point of it. People you trusted are gone and the teaching keeps shifting, but the one you actually follow hasn't moved. What he was to them yesterday he still is today.",
  "Psalm 139:14": "Fearfully here is closer to awe than to fright. David isn't complimenting himself; the whole psalm is about God knowing him before he had a body. Marvellous are thy works is the praise, and he is the work. That's a steadier foundation than deciding you like what you see.",
  "Psalm 34:18": "Nigh means near. Not on the way, not waiting until you pull yourself together, but near while the heart is still broken. David wrote this after pretending to be insane to escape a king. He knew what it was to be at the bottom and find God already there.",
  "Zephaniah 3:17": "This lands at the end of a book full of judgment, which is what makes it hard to read calmly. God is the one singing. He rejoices over his people with joy and rests in his love, which is language for a man delighted with his bride, not a judge tolerating a verdict.",
  "1 Peter 5:8": "As a roaring lion is a comparison, not a title. Peter says he walks about like one, looking. And the verse right before it is casting all your care upon him. Sober and vigilant isn't panic. It's the steadiness of a man who knows something is hunting and knows who is guarding him.",
  "Revelation 21:4": "God does the wiping himself, which is a strangely personal detail in a book of thrones and trumpets. The list is what goes: death, sorrow, crying, pain. Former things are passed away doesn't mean forgotten. It means finished, the way a fever breaks.",
  "Isaiah 9:6": "Born and given both, which is the whole mystery in two words. Then the names pile up on a child: Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace. Isaiah wrote it seven centuries early, to people living under an occupying army in the dark.",
  "Luke 1:37": "Gabriel says this to a young girl who has just asked how any of it could happen. It isn't a general slogan about possibility. He had pointed at Elisabeth, old and expecting, as the evidence. The promise is tied to a specific God doing the specific thing he said he would do.",
  "Acts 2:38": "Peter says this to a crowd that had just realized they helped kill their Messiah and asked what to do. Repent comes first, a change of mind that turns you around. Baptism follows as the public side of it. And the gift is promised to people with nothing to offer but sorrow.",
  "2 Corinthians 12:9": "Paul asked three times for the thorn to go, and this is the answer he got instead. Sufficient is a smaller word than we want and a steadier one. The strength isn't handed over once the weakness clears up. It's made perfect in it, which is why Paul stopped asking and started glorying.",
  "Galatians 5:1": "The yoke Paul warns about isn't a return to open sin. It's rule-keeping, men in Galatia pressing Christians back under a law they had been let out of. Liberty here isn't permission to do as you please. It's freedom from having to earn what Christ already bought.",
  "Psalm 1:1-3": "Watch the drift in the first verse: walketh, standeth, sitteth. Nobody sits down in bad company on the first day. The blessed man's alternative is small and daily, delighting in the law and meditating in it. The tree in verse three isn't lucky. It's planted where the water is.",
  "Joshua 24:15": "Joshua doesn't offer serving nobody as an option. The choice is which god, not whether. He is an old man addressing a nation that has just settled comfortably, and he puts his own household on the line first. As for me and my house is a commitment, not a decoration.",
  "Proverbs 16:3": "Commit is the word for rolling something over onto somebody else. You hand off the weight. What's promised back isn't success but established thoughts, a settled mind. Solomon sets it beside verses about the LORD weighing the spirit, so this isn't a method for getting your plans approved.",
  "1 Thessalonians 5:16-18": "In every thing give thanks is not for every thing. Paul says in, which leaves the hard thing hard and still finds something to thank God for inside it. And this is the will of God concerning you answers, at least in part, a question people spend years asking.",
  "John 8:32": "The verse before it sets the condition: if ye continue in my word. Truth here isn't information in general, it's what Jesus taught, stayed with over time. And the freedom he names next is freedom from sin, not from limits. The people listening insisted they had never been in bondage.",
  "James 4:7": "Two commands, and the order carries the weight. Submitting comes first; resistance without it is only willpower. James is writing to people fighting each other over what they want, so the devil he names isn't an excuse. He's the one taking advantage of a church already at war with itself.",
  "Psalm 51:10": "Create is the word Genesis uses for making something out of nothing. David isn't asking for a cleanup after Bathsheba and Uriah. He is asking for a heart he doesn't have and can't produce. Renew a right spirit admits the same thing twice: the work has to come from outside him.",
};
