/**
 * seo/names.js — biblical names for /bible-names.
 *
 * Different intent from the /verses-about/ person pages: those tell the
 * story, these answer "what does this name mean". Each page links to the
 * other where both exist.
 *
 * lemma, xlit, pron, source and gloss are copied verbatim from the Strong's
 * data already shipped in public/data/strongs (public domain) by
 * seo/build-names.cjs — they are not written by hand. `meaning` is the
 * plain-English rendering, checked against `source` one name at a time;
 * where Strong's calls a derivation uncertain, the meaning says so rather
 * than inventing one. Every page shows `source` so a reader can check it.
 */
export const NAMES = [
  { name: "Aaron", sex: "boy", strongs: "H175", lang: "Hebrew",
    lemma: "אַהֲרוֹן", xlit: "ʼAhărôwn", pron: "a-har-one'",
    meaning: "Uncertain", topic: "aaron",
    source: "of uncertain derivation",
    gloss: "Aharon, the brother of Moses",
    note: "Moses' older brother and Israel's first high priest, who spoke for Moses before Pharaoh." },
  { name: "Abel", sex: "boy", strongs: "H1893", lang: "Hebrew",
    lemma: "הֶבֶל", xlit: "Hebel", pron: "heh'-bel",
    meaning: "Breath", topic: "cain-and-abel",
    source: "the same as H1892 (הֶבֶל)",
    gloss: "Hebel, the son of Adam",
    note: "The second son of Adam, a keeper of sheep, whose offering was accepted and who was killed by his brother." },
  { name: "Abigail", sex: "girl", strongs: "H26", lang: "Hebrew",
    lemma: "אֲבִיגַיִל", xlit: "ʼĂbîygayil", pron: "ab-ee-gah'-yil",
    meaning: "Source of joy", topic: "abigail",
    source: "or shorter אֲבִיגַל; from H1 (אָב) and H1524 (גִּיל); father (i.e. source) of joy",
    gloss: "Abigail or Abigal, the name of two Israelitesses",
    note: "She rode out to meet an armed David with two hundred loaves and a speech that stopped a massacre." },
  { name: "Abraham", sex: "boy", strongs: "H85", lang: "Hebrew",
    lemma: "אַבְרָהָם", xlit: "ʼAbrâhâm", pron: "ab-raw-hawm'",
    meaning: "Father of a multitude", topic: "abraham",
    source: "contracted from H1 (אָב) and an unused root (probably meaning to be populous); father of a multitude",
    gloss: "Abraham, the later name of Abram",
    note: "Called the father of the faithful; the name was given to him at ninety-nine, replacing Abram." },
  { name: "Adam", sex: "boy", strongs: "H121", lang: "Hebrew",
    lemma: "אָדָם", xlit: "ʼÂdâm", pron: "aw-dawm'",
    meaning: "Man", topic: "adam-and-eve",
    source: "the same as H120 (אָדָם)",
    gloss: "Adam the name of the first man, also of a place in Palestine",
    note: "The first man, formed of the dust of the ground — the name and the word for ground are related in Hebrew." },
  { name: "Amos", sex: "boy", strongs: "H5986", lang: "Hebrew",
    lemma: "עָמוֹס", xlit: "ʻÂmôwç", pron: "aw-moce'",
    meaning: "Burden-bearer",
    source: "from H6006 (עָמַס); burdensome",
    gloss: "Amos, an Israelite prophet",
    note: "A herdsman from Tekoa who prophesied against injustice and said he was no prophet by trade." },
  { name: "Andrew", sex: "boy", strongs: "G406", lang: "Greek",
    lemma: "Ἀνδρέας", xlit: "Andréas", pron: "",
    meaning: "Manly", topic: "the-twelve-disciples",
    source: "from G435 (ἀνήρ)",
    gloss: "manly; Andreas, an Israelite",
    note: "Peter's brother, and the first of the disciples to bring somebody else to Jesus." },
  { name: "Anna", sex: "girl", strongs: "G451", lang: "Greek",
    lemma: "Ἄννα", xlit: "Ánna", pron: "",
    meaning: "Favoured", topic: "simeon-and-anna",
    source: "of Hebrew origin (H02584)",
    gloss: "Anna, an Israelitess",
    note: "A prophetess of great age who was in the temple the day Mary and Joseph brought Jesus in." },
  { name: "Asa", sex: "boy", strongs: "H609", lang: "Hebrew",
    lemma: "אָסָא", xlit: "ʼÂçâʼ", pron: "aw-saw'",
    meaning: "Uncertain",
    source: "of uncertain derivation",
    gloss: "Asa, the name of a king and of a Levite",
    note: "A king of Judah who tore down the idols his fathers had set up." },
  { name: "Asher", sex: "boy", strongs: "H836", lang: "Hebrew",
    lemma: "אָשֵׁר", xlit: "ʼÂshêr", pron: "aw-share'",
    meaning: "Happy",
    source: "from H833 (אָשַׁר)",
    gloss: "happy; Asher, a son of Jacob, and the tribe descended from him, with its territory; also a place in Palestine",
    note: "The eighth son of Jacob, whose name his mother gave because of her own gladness." },
  { name: "Barnabas", sex: "boy", strongs: "G921", lang: "Greek",
    lemma: "Βαρνάβας", xlit: "Barnábas", pron: "",
    meaning: "Son of consolation", topic: "barnabas",
    source: "of Chaldee origin (H01247 and H05029)",
    gloss: "son of Nabas (i.e. prophecy); Barnabas, an Israelite",
    note: "Acts gives the translation itself. He vouched for Paul when the church still feared him." },
  { name: "Benjamin", sex: "boy", strongs: "H1144", lang: "Hebrew",
    lemma: "בִּנְיָמִין", xlit: "Binyâmîyn", pron: "bin-yaw-mene'",
    meaning: "Son of the right hand",
    source: "from H1121 (בֵּן) and H3225 (יָמִין); son of (the) right hand",
    gloss: "Binjamin, youngest son of Jacob; also the tribe descended from him, and its territory",
    note: "Jacob's youngest son; his mother named him Benoni as she died and his father renamed him." },
  { name: "Boaz", sex: "boy", strongs: "H1162", lang: "Hebrew",
    lemma: "בֹּעַז", xlit: "Bôʻaz", pron: "bo'-az",
    meaning: "Uncertain", topic: "boaz",
    source: "from an unused root of uncertain meaning",
    gloss: "Boaz, the ancestor of David; also the name of a pillar in front of the temple",
    note: "The kinsman redeemer in the book of Ruth, and an ancestor of David and of Christ." },
  { name: "Caleb", sex: "boy", strongs: "H3612", lang: "Hebrew",
    lemma: "כָּלֵב", xlit: "Kâlêb", pron: "kaw-labe'",
    meaning: "Uncertain", topic: "caleb",
    source: "perhaps a form of H3611 (כֶּלֶב), or else from the same root in the sense of forcible",
    gloss: "Caleb, the name of three Israelites",
    note: "One of two spies who said Israel could take the land, and who asked for the hill country at eighty-five." },
  { name: "Candace", sex: "girl", strongs: "G2582", lang: "Greek",
    lemma: "Κανδάκη", xlit: "Kandákē", pron: "",
    meaning: "Uncertain",
    source: "of foreign origin",
    gloss: "Candacè, an Egyptian queen",
    note: "The title of the Ethiopian queen whose treasurer Philip met on the road to Gaza." },
  { name: "Chloe", sex: "girl", strongs: "G5514", lang: "Greek",
    lemma: "Χλόη", xlit: "Chlóē", pron: "",
    meaning: "Green shoot",
    source: "feminine of apparently a primary word",
    gloss: "\"green\"; Chloë, a Christian female",
    note: "A woman in Corinth whose household told Paul about the divisions in that church." },
  { name: "Claudia", sex: "girl", strongs: "G2803", lang: "Greek",
    lemma: "Κλαυδία", xlit: "Klaudía", pron: "",
    meaning: "Uncertain",
    source: "feminine of G2804 (Κλαύδιος)",
    gloss: "Claudia, a Christian woman",
    note: "A believer in Rome who sent greetings in Paul's last letter to Timothy." },
  { name: "Damaris", sex: "girl", strongs: "G1152", lang: "Greek",
    lemma: "Δάμαρις", xlit: "Dámaris", pron: "",
    meaning: "Gentle",
    source: "probably from the base of G1150 (δαμάζω)",
    gloss: "perhaps gentle; Damaris, an Athenian woman",
    note: "An Athenian woman who believed after hearing Paul speak at the Areopagus." },
  { name: "Dan", sex: "boy", strongs: "H1835", lang: "Hebrew",
    lemma: "דָּן", xlit: "Dân", pron: "dawn",
    meaning: "Judge",
    source: "from H1777 (דִּין); judge",
    gloss: "Dan, one of the sons of Jacob; also the tribe descended from him, and its territory; likewise a place in Palestine colonized by them",
    note: "Jacob's fifth son. Rachel named him, saying God had judged her case and given her a son." },
  { name: "Daniel", sex: "boy", strongs: "H1840", lang: "Hebrew",
    lemma: "דָנִיֵּאל", xlit: "Dânîyêʼl", pron: "daw-nee-yale'",
    meaning: "God is my judge", topic: "daniel",
    source: "in Ezekiel it is; דָּנִאֵל; from H1835 (דָּן) and H410 (אֵל); judge of God",
    gloss: "Daniel or Danijel, the name of two Israelites",
    note: "Taken to Babylon as a youth, he served four kings and kept praying with the window open." },
  { name: "David", sex: "boy", strongs: "H1732", lang: "Hebrew",
    lemma: "דָּוִד", xlit: "Dâvid", pron: "daw-veed'",
    meaning: "Beloved", topic: "david",
    source: "rarely (fully); דָּוִיד; from the same as H1730 (דּוֹד); loving",
    gloss: "David, the youngest son of Jesse",
    note: "The shepherd who killed Goliath, the king who wrote much of the Psalms, called a man after God's own heart." },
  { name: "Deborah", sex: "girl", strongs: "H1683", lang: "Hebrew",
    lemma: "דְּבּוֹרָה", xlit: "Dᵉbôwrâh", pron: "deb-o-raw'",
    meaning: "Bee", topic: "deborah",
    source: "or (shortened) דְּבֹרָה; the same as H1682 (דְּבוֹרָה)",
    gloss: "Deborah, the name of two Hebrewesses",
    note: "A prophetess and the only woman among Israel's judges, who held court under a palm tree." },
  { name: "Delilah", sex: "girl", strongs: "H1807", lang: "Hebrew",
    lemma: "דְּלִילָה", xlit: "Dᵉlîylâh", pron: "del-ee-law'",
    meaning: "Languishing", topic: "samson-and-delilah",
    source: "from H1809 (דָּלַל); languishing",
    gloss: "Delilah, a Philistine woman",
    note: "The woman who asked Samson four times where his strength lay and sold the answer." },
  { name: "Dinah", sex: "girl", strongs: "H1783", lang: "Hebrew",
    lemma: "דִּינָה", xlit: "Dîynâh", pron: "dee-naw'",
    meaning: "Judged", topic: "rachel-and-leah",
    source: "feminine of H1779 (דִּין); justice",
    gloss: "Dinah, the daughter of Jacob",
    note: "Jacob and Leah's daughter, whose story in Genesis 34 is one of the hardest in the book." },
  { name: "Eli", sex: "boy", strongs: "H5941", lang: "Hebrew",
    lemma: "עֵלִי", xlit: "ʻÊlîy", pron: "ay-lee'",
    meaning: "Lofty",
    source: "from H5927 (עָלָה); lofty",
    gloss: "Eli, an Israelite highpriest",
    note: "The high priest who raised Samuel and who mistook Hannah's praying for drunkenness." },
  { name: "Elijah", sex: "boy", strongs: "H452", lang: "Hebrew",
    lemma: "אֵלִיָּה", xlit: "ʼÊlîyâh", pron: "ay-lee-yaw'",
    meaning: "The LORD is my God", topic: "elijah",
    source: "or prolonged אֵלִיָּהוּ; from H410 (אֵל) and H3050 (יָהּ); God of Jehovah",
    gloss: "Elijah, the name of the famous prophet and of two other Israelites",
    note: "The prophet who called down fire on Carmel and heard God afterwards in a still small voice." },
  { name: "Elisabeth", sex: "girl", strongs: "G1665", lang: "Greek",
    lemma: "Ἐλισάβετ", xlit: "Elisábet", pron: "",
    meaning: "Oath of God", topic: "simeon-and-anna",
    source: "of Hebrew origin (H0472)",
    gloss: "Elisabet, an Israelitess",
    note: "Mary's older cousin, who conceived John the Baptist in old age." },
  { name: "Elisha", sex: "boy", strongs: "H477", lang: "Hebrew",
    lemma: "אֱלִישָׁע", xlit: "ʼĔlîyshâʻ", pron: "el-ee-shaw'",
    meaning: "God is salvation", topic: "elisha",
    source: "contracted for H474 (אֱלִישׁוּעַ).",
    gloss: "Elisha, the famous prophet",
    note: "Elijah's successor, who asked for a double portion and whose ministry is full of ordinary need met." },
  { name: "Enoch", sex: "boy", strongs: "H2585", lang: "Hebrew",
    lemma: "חֲנוֹךְ", xlit: "Chănôwk", pron: "khan-oke'",
    meaning: "Dedicated", topic: "enoch",
    source: "from H2596 (חָנַךְ); initiated",
    gloss: "Chanok, an antediluvian patriach",
    note: "He walked with God, and he was not, for God took him — four verses and one of scripture's strangest lines." },
  { name: "Ephraim", sex: "boy", strongs: "H669", lang: "Hebrew",
    lemma: "אֶפְרַיִם", xlit: "ʼEphrayim", pron: "ef-rah'-yim",
    meaning: "Doubly fruitful",
    source: "dual of masculine form of H672 (אֶפְרָת); double fruit",
    gloss: "Ephrajim, a son of Joseph; also the tribe descended from him, and its territory",
    note: "Joseph's second son, born in Egypt, who received the greater blessing from Jacob." },
  { name: "Esther", sex: "girl", strongs: "H635", lang: "Hebrew",
    lemma: "אֶסְתֵּר", xlit: "ʼEçtêr", pron: "es-tare'",
    meaning: "Of Persian origin", topic: "esther",
    source: "of Persian derivation",
    gloss: "Ester, the Jewish heroine",
    note: "Queen of Persia, who used the position to stop a massacre; the book never names God." },
  { name: "Ethan", sex: "boy", strongs: "H387", lang: "Hebrew",
    lemma: "אֵיתָן", xlit: "ʼÊythân", pron: "ay-thawn'",
    meaning: "Enduring",
    source: "the same as H386 (אֵיתָן); permanent",
    gloss: "Ethan, the name of four Israelites",
    note: "Named among the wisest men of his age, and credited with Psalm 89." },
  { name: "Eunice", sex: "girl", strongs: "G2131", lang: "Greek",
    lemma: "Εὐνίκη", xlit: "Euníkē", pron: "",
    meaning: "Victorious", topic: "timothy",
    source: "from G2095 (εὖ) and G3529 (νίκη)",
    gloss: "victorious; Eunice, a Jewess",
    note: "Timothy's mother, named by Paul along with his grandmother Lois for the faith she passed on." },
  { name: "Eve", sex: "girl", strongs: "H2332", lang: "Hebrew",
    lemma: "חַוָּה", xlit: "Chavvâh", pron: "khav-vaw'",
    meaning: "Life-giver", topic: "adam-and-eve",
    source: "causatively from H2331 (חָוָה); life-giver",
    gloss: "Chavvah (or Eve), the first woman",
    note: "The first woman; Adam named her so because she was the mother of all living." },
  { name: "Ezekiel", sex: "boy", strongs: "H3168", lang: "Hebrew",
    lemma: "יְחֶזְקֵאל", xlit: "Yᵉchezqêʼl", pron: "yekh-ez-kale'",
    meaning: "God will strengthen", topic: "ezekiel",
    source: "from H2388 (חָזַק) and H410 (אֵל); God will strengthen",
    gloss: "Jechezkel, the name of two Israelites",
    note: "A priest carried to Babylon who prophesied to exiles, often by acting things out." },
  { name: "Ezra", sex: "boy", strongs: "H5830", lang: "Hebrew",
    lemma: "עֶזְרָא", xlit: "ʻEzrâʼ", pron: "ez-raw'",
    meaning: "Help", topic: "ezra",
    source: "a variation of H5833 (עֶזְרָה)",
    gloss: "Ezra, an Israelite",
    note: "The scribe who led a return from exile and set himself to seek the law, do it, and teach it." },
  { name: "Gabriel", sex: "boy", strongs: "G1043", lang: "Greek",
    lemma: "Γαβριήλ", xlit: "Gabriḗl", pron: "",
    meaning: "Man of God", topic: "angels",
    source: "of Hebrew origin (H01403)",
    gloss: "Gabriel, an archangel",
    note: "The angel who announced the births of John the Baptist and of Jesus." },
  { name: "Gad", sex: "boy", strongs: "H1410", lang: "Hebrew",
    lemma: "גָּד", xlit: "Gâd", pron: "gawd",
    meaning: "Troop",
    source: "from H1464 (גּוּד)",
    gloss: "Gad, a son of Jacob, including his tribe and its territory; also a prophet",
    note: "Jacob's seventh son, and also the name of a prophet who advised David." },
  { name: "Gideon", sex: "boy", strongs: "H1439", lang: "Hebrew",
    lemma: "גִּדְעוֹן", xlit: "Gidʻôwn", pron: "ghid-ohn'",
    meaning: "Feller", topic: "gideon",
    source: "from H1438 (גָּדַע); feller (i.e. warrior)",
    gloss: "Gidon, an Israelite",
    note: "Threshing wheat in a winepress when he was greeted as a mighty man of valour." },
  { name: "Hannah", sex: "girl", strongs: "H2584", lang: "Hebrew",
    lemma: "חַנָּה", xlit: "Channâh", pron: "khan-naw'",
    meaning: "Favoured", topic: "hannah",
    source: "from H2603 (חָנַן); favored",
    gloss: "Channah, an Israelitess",
    note: "She prayed for a son so intensely the priest thought her drunk, and gave Samuel back when he came." },
  { name: "Hezekiah", sex: "boy", strongs: "H2396", lang: "Hebrew",
    lemma: "חִזְקִיָּה", xlit: "Chizqîyâh", pron: "khiz-kee-yaw'",
    meaning: "Strengthened of the LORD", topic: "hezekiah",
    source: "or חִזְקִיָּהוּ; also יְחִזְקִיָּה; or יְחִזְקִיָּהוּ; from H2388 (חָזַק) and H3050 (יָהּ); strengthened of Jah",
    gloss: "Chizkijah, a king of Judah, also the name of two other Israelites",
    note: "He tore down the high places and spread an enemy's threatening letter out before the LORD." },
  { name: "Isaac", sex: "boy", strongs: "G2464", lang: "Greek",
    lemma: "Ἰσαάκ", xlit: "Isaák", pron: "",
    meaning: "He laughs", topic: "isaac",
    source: "of Hebrew origin (H03327)",
    gloss: "Isaac (i.e. Jitschak), the son of Abraham",
    note: "The son of promise, born to parents past the age for it; his mother laughed when she first heard." },
  { name: "Isaiah", sex: "boy", strongs: "H3470", lang: "Hebrew",
    lemma: "יְשַׁעְיָה", xlit: "Yᵉshaʻyâh", pron: "yesh-ah-yaw'",
    meaning: "The LORD has saved", topic: "isaiah",
    source: "or יְשַׁעְיָהוּ; from H3467 (יָשַׁע) and H3050 (יָהּ); Jah has saved",
    gloss: "Jeshajah, the name of seven Israelites",
    note: "The prophet of the child born, the suffering servant, and wings as eagles." },
  { name: "Israel", sex: "boy", strongs: "H3478", lang: "Hebrew",
    lemma: "יִשְׂרָאֵל", xlit: "Yisrâʼêl", pron: "yis-raw-ale'",
    meaning: "He will rule as God", topic: "jacob",
    source: "from H8280 (שָׂרָה) and H410 (אֵל); he will rule as God",
    gloss: "Jisrael, a symbolical name of Jacob; also (typically) of his posterity",
    note: "The name given to Jacob after he wrestled until daybreak, and then to the whole nation." },
  { name: "Jacob", sex: "boy", strongs: "H3290", lang: "Hebrew",
    lemma: "יַעֲקֹב", xlit: "Yaʻăqôb", pron: "yah-ak-obe'",
    meaning: "Heel-catcher", topic: "jacob",
    source: "from H6117 (עָקַב); heel-catcher (i.e. supplanter)",
    gloss: "Jaakob, the Israelitish patriarch",
    note: "Born holding his twin's heel; he bought a birthright, stole a blessing, and had his name changed." },
  { name: "James", sex: "boy", strongs: "G2385", lang: "Greek",
    lemma: "Ἰάκωβος", xlit: "Iákōbos", pron: "",
    meaning: "Heel-catcher",
    source: "the same as G2384 (Ἰακώβ) Græcized",
    gloss: "Jacobus, the name of three Israelites",
    note: "The Greek form of Jacob. Two apostles and the writer of the epistle bore it." },
  { name: "Jared", sex: "boy", strongs: "H3382", lang: "Hebrew",
    lemma: "יֶרֶד", xlit: "Yered", pron: "yeh'-red",
    meaning: "Descent",
    source: "from H3381 (יָרַד); a descent",
    gloss: "Jered, the name of an antediluvian, and of an Israelite",
    note: "One of the patriarchs before the flood, and the father of Enoch." },
  { name: "Jason", sex: "boy", strongs: "G2394", lang: "Greek",
    lemma: "Ἰάσων", xlit: "Iásōn", pron: "",
    meaning: "Healer",
    source: "future active participle masculine of G2390 (ἰάομαι)",
    gloss: "about to cure; Jason, a Christian",
    note: "A believer in Thessalonica who housed Paul and was dragged before the rulers for it." },
  { name: "Jeremiah", sex: "boy", strongs: "H3414", lang: "Hebrew",
    lemma: "יִרְמְיָה", xlit: "Yirmᵉyâh", pron: "yir-meh-yaw'",
    meaning: "The LORD will lift up", topic: "jeremiah",
    source: "or יִרְמְיָהוּ; from H7311 (רוּם) and H3050 (יָהּ); Jah will rise",
    gloss: "Jirmejah, the name of eight or nine Israelites",
    note: "The weeping prophet, who preached forty years to people who would not listen." },
  { name: "Jesse", sex: "boy", strongs: "G2421", lang: "Greek",
    lemma: "Ἰεσσαί", xlit: "Iessaí", pron: "",
    meaning: "Uncertain", topic: "david",
    source: "of Hebrew origin (H03448)",
    gloss: "Jessæ (i.e. Jishai), an Israelite",
    note: "David's father, a Bethlehemite; Isaiah calls the Messiah a rod out of the stem of Jesse." },
  { name: "Joanna", sex: "girl", strongs: "G2489", lang: "Greek",
    lemma: "Ἰωάννα", xlit: "Iōánna", pron: "",
    meaning: "The LORD is gracious",
    source: "feminine of the same as G2491 (Ἰωάννης)",
    gloss: "Joanna, a Christian",
    note: "One of the women who supported Jesus' ministry and who found the tomb empty." },
  { name: "Joel", sex: "boy", strongs: "H3100", lang: "Hebrew",
    lemma: "יוֹאֵל", xlit: "Yôwʼêl", pron: "yo-ale'",
    meaning: "The LORD is God",
    source: "from H3068 (יְהֹוָה) and H410 (אֵל); Jehovah (is his) God",
    gloss: "Joel, the name of twelve Israelites",
    note: "A prophet whose book promises restored years and the Spirit poured out on all flesh." },
  { name: "John", sex: "boy", strongs: "G2491", lang: "Greek",
    lemma: "Ἰωάννης", xlit: "Iōánnēs", pron: "",
    meaning: "The LORD is gracious", topic: "john-the-baptist",
    source: "of Hebrew origin (H03110)",
    gloss: "Joannes (i.e. Jochanan), the name of four Israelites",
    note: "Borne by the Baptist and by the apostle Jesus loved, who wrote the Gospel and the Revelation." },
  { name: "Jonah", sex: "boy", strongs: "H3124", lang: "Hebrew",
    lemma: "יוֹנָה", xlit: "Yôwnâh", pron: "yo-naw'",
    meaning: "Dove", topic: "jonah-and-the-whale",
    source: "the same as H3123 (יוֹנָה)",
    gloss: "Jonah, an Israelite",
    note: "He ran from Nineveh, was swallowed and put back on dry land, then sat down angry when the city repented." },
  { name: "Jonathan", sex: "boy", strongs: "H3129", lang: "Hebrew",
    lemma: "יוֹנָתָן", xlit: "Yôwnâthân", pron: "yo-naw-thawn'",
    meaning: "The LORD has given", topic: "jonathan",
    source: "a form of H3083 (יְהוֹנָתָן)",
    gloss: "Jonathan, the name of ten Israelites",
    note: "Saul's son and heir, who handed David his robe and sword knowing what it cost him." },
  { name: "Joseph", sex: "boy", strongs: "H3084", lang: "Hebrew",
    lemma: "יְהוֹסֵף", xlit: "Yᵉhôwçêph", pron: "yeh-ho-safe'",
    meaning: "He will add", topic: "joseph",
    source: "a fuller form of H3130 (יוֹסֵף)",
    gloss: "Jehoseph (i.e. Joseph), a son of Jacob",
    note: "Sold by his brothers and raised to second in Egypt; ye thought evil, but God meant it unto good." },
  { name: "Joshua", sex: "boy", strongs: "H3091", lang: "Hebrew",
    lemma: "יְהוֹשׁוּעַ", xlit: "Yᵉhôwshûwaʻ", pron: "yeh-ho-shoo'-ah",
    meaning: "The LORD is salvation", topic: "joshua",
    source: "or יְהוֹשֻׁעַ; from H3068 (יְהֹוָה) and H3467 (יָשַׁע); Jehovah-saved",
    gloss: "Jehoshua (i.e. Joshua), the Jewish leader",
    note: "Moses' successor, who led Israel over the Jordan and made the nation choose at the end of his life." },
  { name: "Josiah", sex: "boy", strongs: "H2977", lang: "Hebrew",
    lemma: "יֹאשִׁיָּה", xlit: "Yôʼshîyâh", pron: "yo-shee-yaw'",
    meaning: "Founded of the LORD", topic: "josiah",
    source: "or יֹאשִׁיָּהוּ; from the same root as H803 (אֲשׁוּיָה) and H3050 (יָהּ); founded of Jah",
    gloss: "Joshijah, the name of two Israelites",
    note: "King at eight; at twenty-six he heard the lost law read and tore his clothes." },
  { name: "Judah", sex: "boy", strongs: "H3063", lang: "Hebrew",
    lemma: "יְהוּדָה", xlit: "Yᵉhûwdâh", pron: "yeh-hoo-daw'",
    meaning: "Praised",
    source: "from H3034 (יָדָה); celebrated",
    gloss: "Jehudah (or Judah), the name of five Israelites; also of the tribe descended from the first, and of its territory",
    note: "Jacob's fourth son, the tribe of David and of Christ, called a lion's whelp in his father's blessing." },
  { name: "Jude", sex: "boy", strongs: "G2455", lang: "Greek",
    lemma: "Ἰούδας", xlit: "Ioúdas", pron: "",
    meaning: "Praised",
    source: "of Hebrew origin (H03063)",
    gloss: "Judas (i.e. Jehudah), the name of ten Israelites; also of the posterity of one of them and its region",
    note: "The Greek form of Judah. The writer of the short letter near the end of the New Testament." },
  { name: "Julia", sex: "girl", strongs: "G2456", lang: "Greek",
    lemma: "Ἰουλία", xlit: "Ioulía", pron: "",
    meaning: "Uncertain",
    source: "feminine of the same as G2457 (Ἰούλιος)",
    gloss: "Julia, a Christian woman",
    note: "A believer in Rome greeted by name at the end of Paul's letter." },
  { name: "Keturah", sex: "girl", strongs: "H6989", lang: "Hebrew",
    lemma: "קְטוּרָה", xlit: "Qᵉṭûwrâh", pron: "ket-oo-raw'",
    meaning: "Perfumed", topic: "abraham",
    source: "feminine passive participle of H6999 (קָטַר); perfumed",
    gloss: "Keturah, a wife of Abraham",
    note: "Abraham's wife after Sarah died, and the mother of six more sons." },
  { name: "Keziah", sex: "girl", strongs: "H7103", lang: "Hebrew",
    lemma: "קְצִיעָה", xlit: "Qᵉtsîyʻâh", pron: "kets-ee-aw'",
    meaning: "Cassia", kjv: "Kezia", topic: "job",
    source: "the same as H7102 (קְצִיעָה)",
    gloss: "Ketsiah, a daughter of Job",
    note: "One of three daughters born to Job after his restoration, said to be the fairest in the land." },
  { name: "Leah", sex: "girl", strongs: "H3812", lang: "Hebrew",
    lemma: "לֵאָה", xlit: "Lêʼâh", pron: "lay-aw'",
    meaning: "Weary", topic: "rachel-and-leah",
    source: "from H3811 (לָאָה); weary",
    gloss: "Leah, a wife of Jacob",
    note: "Jacob's first wife, unloved and fruitful; scripture says God saw it and opened her womb." },
  { name: "Levi", sex: "boy", strongs: "G3017", lang: "Greek",
    lemma: "Λευΐ", xlit: "Leuḯ", pron: "",
    meaning: "Joined",
    source: "of Hebrew origin (H03878)",
    gloss: "Levi, the name of three Israelites",
    note: "Jacob's third son and the priestly tribe; also the tax collector who became Matthew." },
  { name: "Lois", sex: "girl", strongs: "G3090", lang: "Greek",
    lemma: "Λωΐς", xlit: "Lōḯs", pron: "",
    meaning: "Uncertain", topic: "timothy",
    source: "of uncertain origin",
    gloss: "Lois, a Christian woman",
    note: "Timothy's grandmother, credited by Paul with the unfeigned faith that reached her grandson." },
  { name: "Luke", sex: "boy", strongs: "G3065", lang: "Greek",
    lemma: "Λουκᾶς", xlit: "Loukâs", pron: "",
    meaning: "Uncertain",
    source: "contracted from Latin Lucanus",
    gloss: "Lucas, a Christian",
    note: "The physician who travelled with Paul and wrote both a Gospel and the book of Acts." },
  { name: "Lydia", sex: "girl", strongs: "G3070", lang: "Greek",
    lemma: "Λυδία", xlit: "Lydía", pron: "",
    meaning: "Of Lydia", topic: "lydia",
    source: "properly, feminine of Ludios (of foreign origin) (a Lydian, in Asia Minor)",
    gloss: "Lydia, a Christian woman",
    note: "A seller of purple whose heart the Lord opened by a river, and the first convert in Europe named." },
  { name: "Malachi", sex: "boy", strongs: "H4401", lang: "Hebrew",
    lemma: "מַלְאָכִי", xlit: "Malʼâkîy", pron: "mal-aw-kee'",
    meaning: "My messenger",
    source: "from the same as H4397 (מֲלְאָךְ); ministrative",
    gloss: "Malaki, a prophet",
    note: "The last prophet of the Old Testament, who closes it looking forward to one who is coming." },
  { name: "Mark", sex: "boy", strongs: "G3138", lang: "Greek",
    lemma: "Μάρκος", xlit: "Márkos", pron: "",
    meaning: "Uncertain", topic: "barnabas",
    source: "of Latin origin",
    gloss: "Marcus, a Christian",
    note: "He turned back partway through Paul's first missionary trip and was given a second chance by Barnabas; he wrote the second Gospel." },
  { name: "Martha", sex: "girl", strongs: "G3136", lang: "Greek",
    lemma: "Μάρθα", xlit: "Mártha", pron: "",
    meaning: "Mistress", topic: "martha-and-mary",
    source: "probably of Chaldee origin (meaning mistress)",
    gloss: "Martha, a Christian woman",
    note: "She complained about the cooking and later made one of the clearest confessions in the Gospels." },
  { name: "Mary", sex: "girl", strongs: "G3137", lang: "Greek",
    lemma: "Μαρία", xlit: "María", pron: "",
    meaning: "Uncertain; the Greek form of Miriam", topic: "mary-the-mother-of-jesus",
    source: "of Hebrew origin (H04813)",
    gloss: "Maria or Mariam (i.e. Mirjam), the name of six Christian females",
    note: "The mother of Jesus, and the name of several other women in the Gospels including Magdalene." },
  { name: "Matthew", sex: "boy", strongs: "G3156", lang: "Greek",
    lemma: "Ματθαῖος", xlit: "Matthaîos", pron: "",
    meaning: "Gift of the LORD", topic: "the-twelve-disciples",
    source: "Greek form of the Hebrew Mattithyâh (H4993): or מַתִּתְיָהוּ; from H4991 (מַתָּת) and H3050 (יָהּ); gift of Jah",
    gloss: "Matthæus (i.e. Matthitjah), an Israelite and a Christian",
    note: "A tax collector who got up from the table and followed, and who wrote the first Gospel." },
  { name: "Micah", sex: "boy", strongs: "H4318", lang: "Hebrew",
    lemma: "מִיכָה", xlit: "Mîykâh", pron: "mee-kaw'",
    meaning: "Who is like the LORD",
    source: "an abbreviated form of H4320 (מִיכָיָה)",
    gloss: "Micah, the name of seven Israelites",
    note: "The prophet who asked what the LORD requires: to do justly, love mercy, and walk humbly." },
  { name: "Michael", sex: "boy", strongs: "H4317", lang: "Hebrew",
    lemma: "מִיכָאֵל", xlit: "Mîykâʼêl", pron: "me-kaw-ale'",
    meaning: "Who is like God", topic: "angels",
    source: "from H4310 (מִי) and (the prefix derivative from) H3588 (כִּי) and H410 (אֵל); who (is) like God?",
    gloss: "Mikael, the name of an archangel and of nine Israelites",
    note: "The archangel named in Daniel, Jude and Revelation, described as standing for God's people." },
  { name: "Michal", sex: "girl", strongs: "H4324", lang: "Hebrew",
    lemma: "מִיכָל", xlit: "Mîykâl", pron: "me-kawl'",
    meaning: "Brook",
    source: "apparently the same as H4323 (מִיכָל); revulet",
    gloss: "Mikal, Saul's daughter",
    note: "Saul's daughter and David's first wife, who let him down out of a window to save his life." },
  { name: "Miriam", sex: "girl", strongs: "H4813", lang: "Hebrew",
    lemma: "מִרְיָם", xlit: "Miryâm", pron: "meer-yawm'",
    meaning: "Rebellion", topic: "miriam",
    source: "from H4805 (מְרִי); rebelliously",
    gloss: "Mirjam, the name of two Israelitesses",
    note: "Moses' sister, who watched his basket on the Nile and led the women in song after the sea." },
  { name: "Moses", sex: "boy", strongs: "H4872", lang: "Hebrew",
    lemma: "מֹשֶׁה", xlit: "Môsheh", pron: "mo-sheh'",
    meaning: "Drawn out", topic: "moses",
    source: "from H4871 (מָשָׁה); drawing out (of the water), i.e. rescued",
    gloss: "Mosheh, the Israelite lawgiver",
    note: "Drawn out of the Nile, raised in Pharaoh's house, and sent back at eighty to lead a nation out." },
  { name: "Naomi", sex: "girl", strongs: "H5281", lang: "Hebrew",
    lemma: "נׇעֳמִי", xlit: "Noʻŏmîy", pron: "no-om-ee'",
    meaning: "Pleasant", topic: "naomi",
    source: "from H5278 (נֹעַם); pleasant",
    gloss: "Noomi, an Israelitess",
    note: "She went to Moab full and came back empty, and asked to be called Mara instead." },
  { name: "Naphtali", sex: "boy", strongs: "H5321", lang: "Hebrew",
    lemma: "נַפְתָּלִי", xlit: "Naphtâlîy", pron: "naf-taw-lee'",
    meaning: "My wrestling",
    source: "from H6617 (פָּתַל); my wrestling",
    gloss: "Naphtali, a son of Jacob, with the tribe descended from him, and its territory",
    note: "Jacob's sixth son, named for the struggle between Rachel and Leah." },
  { name: "Nathan", sex: "boy", strongs: "H5416", lang: "Hebrew",
    lemma: "נָתָן", xlit: "Nâthân", pron: "naw-thawn'",
    meaning: "Given", topic: "david",
    source: "from H5414 (נָתַן); given",
    gloss: "Nathan, the name of five Israelites",
    note: "The prophet who told David a story about a lamb and then said, thou art the man." },
  { name: "Nathanael", sex: "boy", strongs: "G3482", lang: "Greek",
    lemma: "Ναθαναήλ", xlit: "Nathanaḗl", pron: "",
    meaning: "Gift of God", topic: "the-twelve-disciples",
    source: "of Hebrew origin (H05417)",
    gloss: "Nathanaël (i.e. Nathanel), an Israelite and Christian",
    note: "He asked whether any good thing could come out of Nazareth, and was called a man without guile." },
  { name: "Nehemiah", sex: "boy", strongs: "H5166", lang: "Hebrew",
    lemma: "נְחֶמְיָה", xlit: "Nᵉchemyâh", pron: "nekh-em-yaw'",
    meaning: "Comfort of the LORD", topic: "nehemiah",
    source: "from H5162 (נָחַם) and H3050 (יָהּ); consolation of Jah",
    gloss: "Nechemjah, the name of three Israelites",
    note: "A cupbearer who asked leave to rebuild a ruined wall and finished it in fifty-two days." },
  { name: "Noah", sex: "boy", strongs: "H5146", lang: "Hebrew",
    lemma: "נֹחַ", xlit: "Nôach", pron: "no'-akh",
    meaning: "Rest", topic: "noah",
    source: "the same as H5118 (נוּחַ); rest",
    gloss: "Noach, the patriarch of the flood",
    note: "He built a boat for years while the ground stayed dry, and God shut the door behind him." },
  { name: "Obadiah", sex: "boy", strongs: "H5662", lang: "Hebrew",
    lemma: "עֹבַדְיָה", xlit: "ʻÔbadyâh", pron: "o-bad-yaw'",
    meaning: "Servant of the LORD",
    source: "or עֹבַדְיָהוּ; active participle of H5647 (עָבַד) and H3050 (יָהּ); serving Jah",
    gloss: "Obadjah, the name of thirteen Israelites",
    note: "The shortest book in the Old Testament carries this name, borne by more than a dozen men in scripture." },
  { name: "Orpah", sex: "girl", strongs: "H6204", lang: "Hebrew",
    lemma: "עׇרְפָּה", xlit: "ʻOrpâh", pron: "or-paw'",
    meaning: "Mane", topic: "naomi",
    source: "feminine of H6203 (עֹרֶף); mane",
    gloss: "Orpah, a Moabites",
    note: "Ruth's sister-in-law, who kissed Naomi goodbye and went back to her own people." },
  { name: "Paul", sex: "boy", strongs: "G3972", lang: "Greek",
    lemma: "Παῦλος", xlit: "Paûlos", pron: "",
    meaning: "Little", topic: "paul",
    source: "of Latin origin",
    gloss: "(little; but remotely from a derivative of G3973 (παύω), meaning the same); Paulus, the name of a Roman and of an apostle",
    note: "He held the coats at Stephen's stoning, met Christ on the Damascus road, and wrote most of the New Testament." },
  { name: "Peter", sex: "boy", strongs: "G4074", lang: "Greek",
    lemma: "Πέτρος", xlit: "Pétros", pron: "",
    meaning: "Rock", topic: "peter",
    source: "apparently a primary word",
    gloss: "a (piece of) rock (larger than G3037 (λίθος)); as a name, Petrus, an apostle",
    note: "Jesus gave him the name. He walked on water, denied Christ three times, and preached at Pentecost." },
  { name: "Philip", sex: "boy", strongs: "G5376", lang: "Greek",
    lemma: "Φίλιππος", xlit: "Phílippos", pron: "",
    meaning: "Lover of horses", topic: "the-twelve-disciples",
    source: "from G5384 (φίλος) and G2462 (ἵππος)",
    gloss: "fond of horses; Philippus, the name of four Israelites",
    note: "One of the twelve, and also the evangelist who explained Isaiah to an Ethiopian on a desert road." },
  { name: "Phinehas", sex: "boy", strongs: "H6372", lang: "Hebrew",
    lemma: "פִּינְחָס", xlit: "Pîynᵉchâç", pron: "pee-nekh-aws'",
    meaning: "Mouth of a serpent",
    source: "apparently from H6310 (פֶּה) and a variation of H5175 (נָחָשׁ); mouth of a serpent",
    gloss: "Pinechas, the name of three Israelites",
    note: "A grandson of Aaron, remembered for zeal, and the name of two other men in scripture." },
  { name: "Priscilla", sex: "girl", strongs: "G4252", lang: "Greek",
    lemma: "Πρίσκιλλα", xlit: "Prískilla", pron: "",
    meaning: "Little Prisca", topic: "priscilla-and-aquila",
    source: "diminutive of G4251 (Πρίσκα)",
    gloss: "Priscilla (i.e. little Prisca), a Christian woman",
    note: "A tentmaker who, with her husband, took Apollos aside and explained the way of God more perfectly." },
  { name: "Rachel", sex: "girl", strongs: "H7354", lang: "Hebrew",
    lemma: "רָחֵל", xlit: "Râchêl", pron: "raw-khale'",
    meaning: "Ewe", topic: "rachel-and-leah",
    source: "the same as H7353 (רָחֵל)",
    gloss: "Rachel, a wife of Jacob",
    note: "The wife Jacob worked fourteen years for, and the mother of Joseph and Benjamin." },
  { name: "Rebekah", sex: "girl", strongs: "H7259", lang: "Hebrew",
    lemma: "רִבְקָה", xlit: "Ribqâh", pron: "rib-kaw'",
    meaning: "Fettering, as by beauty", topic: "isaac",
    source: "from an unused root probably meaning to clog by tying up the fetlock; fettering (by beauty)",
    gloss: "Ribkah, the wife of Isaac",
    note: "She watered ten camels for a stranger and became Isaac's wife on her own decision to go." },
  { name: "Reuben", sex: "boy", strongs: "H7205", lang: "Hebrew",
    lemma: "רְאוּבֵן", xlit: "Rᵉʼûwbên", pron: "reh-oo-bane'",
    meaning: "Behold, a son",
    source: "from the imperative of H7200 (רָאָה) and H1121 (בֵּן); see ye a son",
    gloss: "Reuben, a son of Jacob",
    note: "Jacob's firstborn, who talked his brothers out of killing Joseph." },
  { name: "Rhoda", sex: "girl", strongs: "G4498", lang: "Greek",
    lemma: "Ῥόδη", xlit: "Rhódē", pron: "",
    meaning: "Rose",
    source: "probably for rhode (a rose)",
    gloss: "Rode, a servant girl",
    note: "The servant girl so glad to hear Peter's voice at the gate that she forgot to open it." },
  { name: "Ruth", sex: "girl", strongs: "H7327", lang: "Hebrew",
    lemma: "רוּת", xlit: "Rûwth", pron: "rooth",
    meaning: "Friend", topic: "ruth",
    source: "probably for H7468 (רְעוּת); friend",
    gloss: "Ruth, a Moabitess",
    note: "A Moabite widow who would not leave her mother-in-law and ended up in the line of David." },
  { name: "Salome", sex: "girl", strongs: "G4539", lang: "Greek",
    lemma: "Σαλώμη", xlit: "Salṓmē", pron: "",
    meaning: "Peaceable", topic: "mary-magdalene",
    source: "probably of Hebrew origin (feminine from H07965)",
    gloss: "Salome (i.e. Shelomah), an Israelitess",
    note: "One of the women at the cross and among the first at the tomb on the third morning." },
  { name: "Samson", sex: "boy", strongs: "H8123", lang: "Hebrew",
    lemma: "שִׁמְשׁוֹן", xlit: "Shimshôwn", pron: "shim-shone'",
    meaning: "Sunlight", topic: "samson-and-delilah",
    source: "from H8121 (שֶׁמֶשׁ); sunlight",
    gloss: "Shimshon, an Israelite",
    note: "The strongest of the judges and the least self-controlled; his last act was his greatest." },
  { name: "Samuel", sex: "boy", strongs: "H8050", lang: "Hebrew",
    lemma: "שְׁמוּאֵל", xlit: "Shᵉmûwʼêl", pron: "sehm-oo-ale'",
    meaning: "Heard of God", topic: "samuel",
    source: "from the passive participle of H8085 (שָׁמַע) and H410 (אֵל); heard of God",
    gloss: "Shemuel, the name of three Israelites",
    note: "Given back to God as a boy, he heard his name called in the night and anointed Israel's first two kings." },
  { name: "Sarah", sex: "girl", strongs: "H8283", lang: "Hebrew",
    lemma: "שָׂרָה", xlit: "Sârâh", pron: "saw-raw'",
    meaning: "Princess", topic: "abraham",
    source: "the same as H8282 (שָׂרָה)",
    gloss: "Sarah, Abraham's wife",
    note: "Abraham's wife, who laughed when she overheard she would bear a son at ninety, then bore him." },
  { name: "Saul", sex: "boy", strongs: "H7586", lang: "Hebrew",
    lemma: "שָׁאוּל", xlit: "Shâʼûwl", pron: "shaw-ool'",
    meaning: "Asked for", topic: "king-saul",
    source: "passive participle of H7592 (שָׁאַל); asked",
    gloss: "Shaul, the name of an Edomite and two Israelites",
    note: "Israel's first king, head and shoulders above the rest, who lost the throne over partial obedience." },
  { name: "Seth", sex: "boy", strongs: "H8352", lang: "Hebrew",
    lemma: "שֵׁת", xlit: "Shêth", pron: "shayth",
    meaning: "Appointed", topic: "adam-and-eve",
    source: "from H7896 (שִׁית); put, i.e. substituted",
    gloss: "Sheth, third son of Adam",
    note: "Adam's third son, given, his mother said, in place of Abel." },
  { name: "Silas", sex: "boy", strongs: "G4609", lang: "Greek",
    lemma: "Σίλας", xlit: "Sílas", pron: "",
    meaning: "Uncertain", topic: "the-philippian-jailer",
    source: "contraction for G4610 (Σιλουανός)",
    gloss: "Silas, a Christian",
    note: "Paul's companion, singing at midnight in the Philippian jail when the earthquake came." },
  { name: "Simeon", sex: "boy", strongs: "G4826", lang: "Greek",
    lemma: "Συμεών", xlit: "Symeṓn", pron: "",
    meaning: "Hearing", topic: "simeon-and-anna",
    source: "from the same as G4613 (Σίμων)",
    gloss: "Symeon (i.e. Shimon), the name of five Israelites",
    note: "Jacob's second son, and the old man in the temple who had been promised he would see the Messiah." },
  { name: "Simon", sex: "boy", strongs: "G4613", lang: "Greek",
    lemma: "Σίμων", xlit: "Símōn", pron: "",
    meaning: "Hearing", topic: "peter",
    source: "of Hebrew origin (H08095)",
    gloss: "Simon (i.e. Shimon), the name of nine Israelites",
    note: "Peter's given name, and the name of several other men in the Gospels and Acts." },
  { name: "Solomon", sex: "boy", strongs: "G4672", lang: "Greek",
    lemma: "Σολομών", xlit: "Solomṓn", pron: "",
    meaning: "Peaceable", topic: "solomon",
    source: "of Hebrew origin (H08010)",
    gloss: "Solomon (i.e. Shelomoh), the son of David",
    note: "He asked for an understanding heart instead of riches, built the temple, and wrote much of Proverbs." },
  { name: "Stephen", sex: "boy", strongs: "G4736", lang: "Greek",
    lemma: "Στέφανος", xlit: "Stéphanos", pron: "",
    meaning: "Crown", topic: "stephen",
    source: "the same as G4735 (στέφανος)",
    gloss: "Stephanus, a Christian",
    note: "Chosen to wait tables, he preached the longest sermon in Acts and was stoned praying for the men doing it." },
  { name: "Susanna", sex: "girl", strongs: "G4677", lang: "Greek",
    lemma: "Σουσάννα", xlit: "Sousánna", pron: "",
    meaning: "Lily",
    source: "of Hebrew origin (H07799 feminine)",
    gloss: "lily; Susannah (i.e. Shoshannah), an Israelitess",
    note: "One of the women named in Luke as supporting Jesus and the twelve out of their own means." },
  { name: "Tabitha", sex: "girl", strongs: "G5000", lang: "Greek",
    lemma: "Ταβιθά", xlit: "Tabithá", pron: "",
    meaning: "Gazelle", topic: "dorcas",
    source: "of Chaldee origin (compare H06646)",
    gloss: "the gazelle; Tabitha (i.e. Tabjetha), a Christian female",
    note: "Full of good works; when she died the widows stood around showing Peter the coats she had made." },
  { name: "Tamar", sex: "girl", strongs: "H8559", lang: "Hebrew",
    lemma: "תָּמָר", xlit: "Tâmâr", pron: "taw-mawr'",
    meaning: "Palm tree",
    source: "the same as H8558 (תָּמָר)",
    gloss: "Tamar, the name of three women and a place",
    note: "Borne by three women in scripture, including one named in the genealogy of Christ." },
  { name: "Thomas", sex: "boy", strongs: "G2381", lang: "Greek",
    lemma: "Θωμᾶς", xlit: "Thōmâs", pron: "",
    meaning: "Twin", topic: "thomas",
    source: "of Chaldee origin (compare H08380)",
    gloss: "the twin; Thomas, a Christian",
    note: "He would not believe without touching the wounds, and made the highest confession in the Gospel." },
  { name: "Timothy", sex: "boy", strongs: "G5095", lang: "Greek",
    lemma: "Τιμόθεος", xlit: "Timótheos", pron: "",
    meaning: "Honouring God", topic: "timothy",
    source: "from G5092 (τιμή) and G2316 (θεός)",
    gloss: "dear to God; Timotheus, a Christian",
    note: "Young, often unwell, pastoring a hard church, and the recipient of two letters that read like a father's." },
  { name: "Tirzah", sex: "girl", strongs: "H8656", lang: "Hebrew",
    lemma: "תִּרְצָה", xlit: "Tirtsâh", pron: "teer-tsaw'",
    meaning: "Delight",
    source: "from H7521 (רָצָה); delightsomeness",
    gloss: "Tirtsah, a place in Palestine; also an Israelitess",
    note: "One of Zelophehad's five daughters, who asked for an inheritance and were granted it." },
  { name: "Titus", sex: "boy", strongs: "G5103", lang: "Greek",
    lemma: "Τίτος", xlit: "Títos", pron: "",
    meaning: "Uncertain",
    source: "of Latin origin but uncertain significance",
    gloss: "Titus, a Christian",
    note: "Paul left him in Crete to set things in order, and wrote him a letter about how." },
  { name: "Uriah", sex: "boy", strongs: "H223", lang: "Hebrew",
    lemma: "אוּרִיָּה", xlit: "ʼÛwrîyâh", pron: "oo-ree-yaw'",
    meaning: "Flame of the LORD",
    source: "or (prolonged) אוּרִיָּהוּ ; from H217 (אוּר) and H3050 (יָהּ); flame of Jah",
    gloss: "Urijah, the name of one Hittite and five Israelites",
    note: "A Hittite in David's army, and one of his mighty men, killed to cover up the king's sin." },
  { name: "Zebulun", sex: "boy", strongs: "H2074", lang: "Hebrew",
    lemma: "זְבוּלוּן", xlit: "Zᵉbûwlûwn", pron: "zeb-oo-loon'",
    meaning: "Dwelling",
    source: "or זְבֻלוּן; or זְבוּלֻן; from H2082 (זָבַל); habitation",
    gloss: "Zebulon, a son of Jacob; also his territory and tribe",
    note: "Jacob's tenth son; Isaiah names his territory as the place a great light would be seen." },
  { name: "Zipporah", sex: "girl", strongs: "H6855", lang: "Hebrew",
    lemma: "צִפֹּרָה", xlit: "Tsippôrâh", pron: "tsip-po-raw'",
    meaning: "Bird", topic: "moses",
    source: "feminine of H6833 (צִפּוֹר); bird",
    gloss: "Tsipporah, Moses' wife",
    note: "Moses' wife, a daughter of the priest of Midian, who met him at a well in the wilderness." },
];
