/**
 * seo/topic-intros.js — original opening paragraphs for the /verses-about/
 * topic pages, written for TheWay.
 *
 * Why this file exists: a topic page is a list of King James verses, and the
 * King James text is public domain. Without an intro, every one of these 290
 * pages says the same boilerplate sentence and is indistinguishable from the
 * dozens of other sites running the same list. This is the only original
 * writing on a topic page, and it is what an AI assistant quotes when somebody
 * asks what the Bible says about a subject.
 *
 * Keyed by topic slug. A topic with no entry falls back to the generic line,
 * so this can be filled in a batch at a time.
 *
 * Batch 1 (Sept 19): the 40 topics with the most search demand — the queries
 * Search Console already shows impressions for ("bible verses about marriage",
 * "bible verses about hope") plus the perennial ones.
 */
export const TOPIC_INTROS = {
  "fear-and-anxiety": "Fear turns up constantly in scripture, and almost never as something to be ashamed of. The command not to be afraid usually comes with a reason attached, and the reason is God rather than the size of the thing in front of you. These verses run from Isaiah to Philippians.",
  "hope": "Hope in the Bible isn't wishing. It's expectation with something solid underneath it, a promise made by somebody who keeps promises. Most of these verses were written to people in exile, in prison, or waiting on something that hadn't come yet, which is why they hold up when a good mood won't.",
  "marriage": "Scripture talks about marriage as a covenant before it talks about it as a feeling. These verses cover what husbands and wives are each told to do, what Jesus said about two becoming one flesh, and what Paul meant by love that suffereth long — the passages read at weddings and the ones that matter afterward.",
  "strength": "The Bible almost never tells a strong person to be strong. These verses land on the tired, the outnumbered and the afraid: Joshua taking over from Moses, Paul with a thorn he couldn't shake, Isaiah writing to people who had nothing left. The strength promised in them comes from outside the person needing it.",
  "healing": "Scripture treats healing as something God does, sometimes through ordinary means and sometimes without them, and it never pretends the sick are at fault. These verses include the ones people pray over a hospital bed and the harder ones about a healing that waits.",
  "gods-love": "God's love in scripture is shown before it is described. It shows up as a Son given, a shepherd going after one sheep, a father running down a road. These verses gather what the Bible says about a love that started first and doesn't rise and fall with how the week went.",
  "faith": "Faith in the Bible isn't believing without a reason. Hebrews calls it substance and evidence, which are solid words. These verses cover what faith is, where it comes from, and what it looks like when somebody acts on what God said before they can see how it turns out.",
  "peace": "Two kinds of peace run through scripture: peace with God, which was settled at the cross, and the peace of God, which keeps guard over a mind while the trouble is still going. These verses cover both, including the ones Jesus spoke the night before he was arrested.",
  "grief-and-loss": "The Bible gives grief room. David wrote songs in it. Jesus wept at a grave he was about to open. Paul told the Thessalonians they would sorrow, just not as people with no hope. These verses sit with loss rather than hurrying anybody past it.",
  "encouragement": "Encouragement in scripture is usually specific — a name, a promise, a reason. These are the verses people send when somebody is worn out: the ones about God going on ahead, holding on, and finishing what he started.",
  "forgiveness": "Forgiveness runs both directions in scripture, and the verses hold the two together on purpose: forgive as you have been forgiven. These cover what God does with confessed sin, what Jesus said about the limit Peter tried to set, and what to do when the other person hasn't asked.",
  "depression": "Scripture doesn't scold people who are low. Elijah asked to die and was fed and let to sleep. David asked his own soul why it was cast down, out loud, more than once. These verses meet discouragement plainly, and many of them were written by people in the middle of it.",
  "protection": "Protection in the Bible is usually pictured rather than stated in the abstract: a refuge, a shield, a high tower, wings. These verses gather those images, including the whole of Psalm 91, along with the ones where protection meant God with somebody in the trouble rather than out of it.",
  "trusting-god": "Trust in scripture is something you lean your weight on. Proverbs sets it against leaning on your own understanding, which isn't an insult to your thinking. It's a statement about how much your thinking can hold. These verses cover trusting God with what you can't see yet.",
  "patience-and-endurance": "The King James word is often longsuffering, which says it better — patience that has to last a while. These verses cover waiting on God, running a race with patience, and the promise in Galatians that the harvest comes if you don't faint first.",
  "money-and-finances": "Scripture talks about money more than most people expect, and it is rarely flattering or condemning on its own. These verses cover giving, debt, contentment, the love of money Paul called a root of evil, and what Jesus said about where a treasure and a heart end up together.",
  "work": "The Bible puts work before the fall, not after it, which changes how the rest of it reads. These verses cover doing it heartily as to the Lord, resting from it, working under a hard employer, and the dignity Paul gave to ordinary labor.",
  "friendship": "Scripture's picture of friendship is loyalty more than company. A friend loveth at all times. Iron sharpeneth iron. Jonathan kept faith with David when it cost him a throne. These verses cover the friendships in the Bible and what they say a real one does.",
  "family": "The Bible's families are not tidy, and it doesn't hide it. These verses cover what is asked of parents, children, husbands and wives, and the households that chose to serve the Lord, alongside the promise that God sets the solitary in families.",
  "children-and-parenting": "Scripture gives parents instruction and comfort in about equal measure. These verses cover training a child, provoking them and not, teaching at home in ordinary hours, and what Jesus said when the disciples tried to keep children away from him.",
  "thankfulness": "Thanksgiving in scripture usually comes before the situation changes rather than after. Paul writes it from prison, and the psalms sing it in the middle of trouble. These verses cover giving thanks in everything, and what the Bible says that does to a person.",
  "prayer": "The Bible teaches prayer mostly by example — people talking to God plainly, including when they are angry. These verses cover how Jesus told his disciples to pray, praying without ceasing, and what happens to worry when it gets said out loud to God.",
  "joy": "Joy in scripture isn't tied to circumstances, which is why so much of it was written by people in bad ones. These verses cover the joy of the LORD as strength, joy that comes in the morning, and the joy Jesus said he wanted his followers to have full.",
  "wisdom": "Wisdom in the Bible begins with the fear of the LORD, which Proverbs treats as a starting point rather than a summary. These verses cover asking God for it, the difference between knowing things and being wise, and what James says God does with anybody who asks.",
  "temptation": "Scripture treats temptation as ordinary and survivable. Paul says none of it is new and that God makes a way out. These verses cover how Jesus answered it in the wilderness, what James says about where it starts, and why fleeing is sometimes the instruction.",
  "courage": "Courage in the Bible rests on a fact rather than a feeling. Be strong and of a good courage comes with the LORD thy God is with thee attached to it. These verses cover the people who were told that and what they had to walk into afterward.",
  "comfort": "The word for comfort in scripture is closer to coming alongside than to soothing. Paul says God comforts us so that we can comfort others with the same comfort we were given. These verses cover that, and the ones people reach for at a graveside.",
  "loneliness": "The Bible says more about being alone than people expect. God called it not good at the very beginning. Elijah was sure he was the only one left and was told otherwise. These verses cover God's presence with people who feel unseen, including the promise never to leave.",
  "worry": "Jesus spent a long stretch of the Sermon on the Mount on worry, and his argument is mostly about birds and flowers, things fed and clothed without anxious effort. These verses cover that passage, Paul's instruction to pray instead of carry, and Peter's line about casting care.",
  "stress": "Scripture doesn't use the word stress, but it is full of people carrying more than they can. Moses was told to share the load. Martha was told her sister had chosen the better part. These verses cover rest, burdens handed off, and the yoke Jesus called easy.",
  "women": "The Bible's women are prophets, judges, queens, business owners and the first people at the empty tomb. These verses gather what scripture says to and about them, including Proverbs 31 read as a whole rather than as a checklist.",
  "men": "Scripture's instruction to men is mostly about how they treat people — wives, children, workers, enemies. These verses cover strength and gentleness held together, the charge Paul gave a young Timothy, and what is asked of a husband and a father.",
  "leadership": "Leadership in the Bible is defined downward. The greatest among you shall be your servant, said to men arguing about rank. These verses cover shepherding rather than lording, the qualifications Paul listed, and the leaders scripture holds up next to the ones it doesn't.",
  "giving-and-generosity": "Scripture ties giving to the heart behind it more than to the amount. A widow's two mites outweighed everything else put in the treasury that day. These verses cover cheerful giving, the tithe, caring for the poor, and what Jesus said about doing it quietly.",
  "humility": "Humility in the Bible isn't thinking poorly of yourself. It's being the right size. God resisteth the proud and giveth grace to the humble. These verses cover Christ emptying himself, the washing of feet, and the promise that God lifts up whoever is willing to go low.",
  "salvation": "These are the verses that say plainly how a person is saved: by grace, through faith, not of works. They cover what Paul wrote to the Romans and the Ephesians, what Jesus told Nicodemus at night, and what Peter preached to a crowd that asked what they should do.",
  "heaven-and-eternity": "Scripture says less about heaven's scenery than people expect and more about who is there. These verses cover the place Jesus said he was going to prepare, the city John saw, the end of tears and death, and what the Bible means when it says for ever.",
  "the-armor-of-god": "Paul lists six pieces in Ephesians 6, and every one of them is worn rather than carried into a fight you picked. These verses cover the whole passage — the belt, breastplate, shoes, shield, helmet and sword — and the line about wrestling not against flesh and blood.",
  "spiritual-warfare": "The Bible's picture of spiritual conflict is defensive more than dramatic. Stand, resist, and submit first. These verses cover the armor in Ephesians, James on resisting the devil, and Paul's reminder that the weapons of this warfare are not carnal.",
  "death": "Scripture calls death an enemy and then says it was swallowed up in victory. These verses cover what the Bible says about dying, what Jesus said standing outside Lazarus's grave, and Paul's question about where death's sting had gone.",
};
