/**
 * seo/topic-intros.js — original opening paragraphs for the /verses-about/
 * topic pages, written for TheWay.
 *
 * Why this file exists: a topic page is a list of King James verses, and the
 * King James text is public domain. Without an intro, every one of these 290
 * pages says the same boilerplate sentence and is indistinguishable from the
 * dozens of other sites running the same list. This is the only original
 * writing on a topic page, and it is what an AI assistant quotes when somebody
 * asks what the Bible says about a subject.
 *
 * Keyed by topic slug. A topic with no entry falls back to the generic line,
 * so this can be filled in a batch at a time.
 *
 * Batch 1 (Sept 19): the 40 topics with the most search demand — the queries
 * Search Console already shows impressions for ("bible verses about marriage",
 * "bible verses about hope") plus the perennial ones.
 * Batch 2 (Sept 19): God's character and the sin/character topics — the next
 * tier of demand, and the ones an assistant is most likely to be asked about.
 */
export const TOPIC_INTROS = {
  "fear-and-anxiety": "Fear turns up constantly in scripture, and almost never as something to be ashamed of. The command not to be afraid usually comes with a reason attached, and the reason is God rather than the size of the thing in front of you. These verses run from Isaiah to Philippians.",
  "hope": "Hope in the Bible isn't wishing. It's expectation with something solid underneath it, a promise made by somebody who keeps promises. Most of these verses were written to people in exile, in prison, or waiting on something that hadn't come yet, which is why they hold up when a good mood won't.",
  "marriage": "Scripture talks about marriage as a covenant before it talks about it as a feeling. These verses cover what husbands and wives are each told to do, what Jesus said about two becoming one flesh, and what Paul meant by love that suffereth long — the passages read at weddings and the ones that matter afterward.",
  "strength": "The Bible almost never tells a strong person to be strong. These verses land on the tired, the outnumbered and the afraid: Joshua taking over from Moses, Paul with a thorn he couldn't shake, Isaiah writing to people who had nothing left. The strength promised in them comes from outside the person needing it.",
  "healing": "Scripture treats healing as something God does, sometimes through ordinary means and sometimes without them, and it never pretends the sick are at fault. These verses include the ones people pray over a hospital bed and the harder ones about a healing that waits.",
  "gods-love": "God's love in scripture is shown before it is described. It shows up as a Son given, a shepherd going after one sheep, a father running down a road. These verses gather what the Bible says about a love that started first and doesn't rise and fall with how the week went.",
  "faith": "Faith in the Bible isn't believing without a reason. Hebrews calls it substance and evidence, which are solid words. These verses cover what faith is, where it comes from, and what it looks like when somebody acts on what God said before they can see how it turns out.",
  "peace": "Two kinds of peace run through scripture: peace with God, which was settled at the cross, and the peace of God, which keeps guard over a mind while the trouble is still going. These verses cover both, including the ones Jesus spoke the night before he was arrested.",
  "grief-and-loss": "The Bible gives grief room. David wrote songs in it. Jesus wept at a grave he was about to open. Paul told the Thessalonians they would sorrow, just not as people with no hope. These verses sit with loss rather than hurrying anybody past it.",
  "encouragement": "Encouragement in scripture is usually specific — a name, a promise, a reason. These are the verses people send when somebody is worn out: the ones about God going on ahead, holding on, and finishing what he started.",
  "forgiveness": "Forgiveness runs both directions in scripture, and the verses hold the two together on purpose: forgive as you have been forgiven. These cover what God does with confessed sin, what Jesus said about the limit Peter tried to set, and what to do when the other person hasn't asked.",
  "depression": "Scripture doesn't scold people who are low. Elijah asked to die and was fed and let to sleep. David asked his own soul why it was cast down, out loud, more than once. These verses meet discouragement plainly, and many of them were written by people in the middle of it.",
  "protection": "Protection in the Bible is usually pictured rather than stated in the abstract: a refuge, a shield, a high tower, wings. These verses gather those images, including the whole of Psalm 91, along with the ones where protection meant God with somebody in the trouble rather than out of it.",
  "trusting-god": "Trust in scripture is something you lean your weight on. Proverbs sets it against leaning on your own understanding, which isn't an insult to your thinking. It's a statement about how much your thinking can hold. These verses cover trusting God with what you can't see yet.",
  "patience-and-endurance": "The King James word is often longsuffering, which says it better — patience that has to last a while. These verses cover waiting on God, running a race with patience, and the promise in Galatians that the harvest comes if you don't faint first.",
  "money-and-finances": "Scripture talks about money more than most people expect, and it is rarely flattering or condemning on its own. These verses cover giving, debt, contentment, the love of money Paul called a root of evil, and what Jesus said about where a treasure and a heart end up together.",
  "work": "The Bible puts work before the fall, not after it, which changes how the rest of it reads. These verses cover doing it heartily as to the Lord, resting from it, working under a hard employer, and the dignity Paul gave to ordinary labor.",
  "friendship": "Scripture's picture of friendship is loyalty more than company. A friend loveth at all times. Iron sharpeneth iron. Jonathan kept faith with David when it cost him a throne. These verses cover the friendships in the Bible and what they say a real one does.",
  "family": "The Bible's families are not tidy, and it doesn't hide it. These verses cover what is asked of parents, children, husbands and wives, and the households that chose to serve the Lord, alongside the promise that God sets the solitary in families.",
  "children-and-parenting": "Scripture gives parents instruction and comfort in about equal measure. These verses cover training a child, provoking them and not, teaching at home in ordinary hours, and what Jesus said when the disciples tried to keep children away from him.",
  "thankfulness": "Thanksgiving in scripture usually comes before the situation changes rather than after. Paul writes it from prison, and the psalms sing it in the middle of trouble. These verses cover giving thanks in everything, and what the Bible says that does to a person.",
  "prayer": "The Bible teaches prayer mostly by example — people talking to God plainly, including when they are angry. These verses cover how Jesus told his disciples to pray, praying without ceasing, and what happens to worry when it gets said out loud to God.",
  "joy": "Joy in scripture isn't tied to circumstances, which is why so much of it was written by people in bad ones. These verses cover the joy of the LORD as strength, joy that comes in the morning, and the joy Jesus said he wanted his followers to have full.",
  "wisdom": "Wisdom in the Bible begins with the fear of the LORD, which Proverbs treats as a starting point rather than a summary. These verses cover asking God for it, the difference between knowing things and being wise, and what James says God does with anybody who asks.",
  "temptation": "Scripture treats temptation as ordinary and survivable. Paul says none of it is new and that God makes a way out. These verses cover how Jesus answered it in the wilderness, what James says about where it starts, and why fleeing is sometimes the instruction.",
  "courage": "Courage in the Bible rests on a fact rather than a feeling. Be strong and of a good courage comes with the LORD thy God is with thee attached to it. These verses cover the people who were told that and what they had to walk into afterward.",
  "comfort": "The word for comfort in scripture is closer to coming alongside than to soothing. Paul says God comforts us so that we can comfort others with the same comfort we were given. These verses cover that, and the ones people reach for at a graveside.",
  "loneliness": "The Bible says more about being alone than people expect. God called it not good at the very beginning. Elijah was sure he was the only one left and was told otherwise. These verses cover God's presence with people who feel unseen, including the promise never to leave.",
  "worry": "Jesus spent a long stretch of the Sermon on the Mount on worry, and his argument is mostly about birds and flowers, things fed and clothed without anxious effort. These verses cover that passage, Paul's instruction to pray instead of carry, and Peter's line about casting care.",
  "stress": "Scripture doesn't use the word stress, but it is full of people carrying more than they can. Moses was told to share the load. Martha was told her sister had chosen the better part. These verses cover rest, burdens handed off, and the yoke Jesus called easy.",
  "women": "The Bible's women are prophets, judges, queens, business owners and the first people at the empty tomb. These verses gather what scripture says to and about them, including Proverbs 31 read as a whole rather than as a checklist.",
  "men": "Scripture's instruction to men is mostly about how they treat people — wives, children, workers, enemies. These verses cover strength and gentleness held together, the charge Paul gave a young Timothy, and what is asked of a husband and a father.",
  "leadership": "Leadership in the Bible is defined downward. The greatest among you shall be your servant, said to men arguing about rank. These verses cover shepherding rather than lording, the qualifications Paul listed, and the leaders scripture holds up next to the ones it doesn't.",
  "giving-and-generosity": "Scripture ties giving to the heart behind it more than to the amount. A widow's two mites outweighed everything else put in the treasury that day. These verses cover cheerful giving, the tithe, caring for the poor, and what Jesus said about doing it quietly.",
  "humility": "Humility in the Bible isn't thinking poorly of yourself. It's being the right size. God resisteth the proud and giveth grace to the humble. These verses cover Christ emptying himself, the washing of feet, and the promise that God lifts up whoever is willing to go low.",
  "salvation": "These are the verses that say plainly how a person is saved: by grace, through faith, not of works. They cover what Paul wrote to the Romans and the Ephesians, what Jesus told Nicodemus at night, and what Peter preached to a crowd that asked what they should do.",
  "heaven-and-eternity": "Scripture says less about heaven's scenery than people expect and more about who is there. These verses cover the place Jesus said he was going to prepare, the city John saw, the end of tears and death, and what the Bible means when it says for ever.",
  "the-armor-of-god": "Paul lists six pieces in Ephesians 6, and every one of them is worn rather than carried into a fight you picked. These verses cover the whole passage — the belt, breastplate, shoes, shield, helmet and sword — and the line about wrestling not against flesh and blood.",
  "spiritual-warfare": "The Bible's picture of spiritual conflict is defensive more than dramatic. Stand, resist, and submit first. These verses cover the armor in Ephesians, James on resisting the devil, and Paul's reminder that the weapons of this warfare are not carnal.",
  "death": "Scripture calls death an enemy and then says it was swallowed up in victory. These verses cover what the Bible says about dying, what Jesus said standing outside Lazarus's grave, and Paul's question about where death's sting had gone.",
  "grace-and-mercy": "Mercy is not getting what you had coming. Grace is getting what you never had coming. Scripture keeps them side by side, and these verses cover both — the God who is slow to anger, the debt cancelled, and Paul's insistence that if it could be earned it wouldn't be grace at all.",
  "obedience": "Obedience in the Bible follows love rather than replacing it. If ye love me, keep my commandments, in that order. These verses cover what God asks, what Samuel told Saul about obeying being better than sacrifice, and the obedience Jesus himself kept all the way to a cross.",
  "repentance": "Repentance isn't feeling bad. The word means turning — a change of mind that changes direction. These verses cover what God does with a broken and a contrite heart, what John and Jesus both opened their preaching with, and the difference Paul drew between godly sorrow and the other kind.",
  "sin": "Scripture is blunt about sin and never only about other people's. All have sinned is written to religious people. These verses cover what sin is, what it pays, what it does to a person's own sense of things, and what God does with it the moment it's confessed.",
  "holy-spirit": "The Holy Spirit in scripture teaches, convicts, comforts, gives gifts, and produces fruit. These verses cover who he is rather than what he feels like — the promise Jesus made before he left, the power at Pentecost, and what Paul says about grieving him.",
  "jesus": "These are the verses that say who Jesus is in scripture's own words: the Word made flesh, the way and the truth and the life, the lamb of God, the firstborn of every creature. They cover his claims about himself and what the apostles wrote about him afterward.",
  "gods-faithfulness": "The Bible's argument for God's faithfulness is usually history, not sentiment. He kept this before, so he will keep it now. These verses cover mercies new every morning, a God who cannot deny himself, and the promises made to people who had no way to make him keep them.",
  "gods-promises": "Scripture treats a promise from God as something to hold him to. Abraham did. So did Moses and David. These verses gather the promises the Bible repeats most, along with Paul's claim that in Christ they are all yea and amen.",
  "gods-presence": "The Bible's comfort is usually presence before it's rescue. I will be with thee shows up more often than I will get you out. These verses cover God with people in fire, in exile, in a valley, and Jesus' last line in Matthew about being with us always.",
  "gods-power": "Scripture shows God's power at work in creation, in resurrection, and in ordinary people who had none of their own. These verses cover what the Bible says he is able to do, including Paul's line about exceeding abundantly above all that we ask or think.",
  "gods-sovereignty": "Sovereignty means God runs things, including the parts nobody would have chosen. Scripture holds that alongside real human choices without apologizing for the tension. These verses cover his rule over nations, over circumstances, and over what Joseph told his brothers about what they meant for evil.",
  "gods-goodness": "The Bible asks people to test this one: O taste and see that the LORD is good. These verses cover his goodness as something experienced rather than assumed, including the psalms written by men who said it while things were still hard.",
  "scripture-and-gods-word": "These verses are the Bible talking about itself — given by inspiration, quick and powerful, a lamp for the next step. They cover what scripture claims to be, what it is for, and Jesus' own habit of answering with it is written.",
  "worship-and-praise": "Worship in scripture is bigger than music and older than buildings. It shows up as bowing, building altars, dancing, singing, and Paul's line about offering your body as a living sacrifice. These verses cover what the Bible calls worship and who it is aimed at.",
  "spiritual-growth": "Growth in scripture is slow and normal — milk before meat, a seed before a harvest, a work God started and intends to finish. These verses cover what grows a believer and what Peter says to add to your faith.",
  "seeking-god": "Seeking in the Bible comes with a promise attached: those who seek find, if they seek with the whole heart. These verses cover seeking early, seeking first, and the God who Isaiah says is found by people who weren't even looking.",
  "righteousness": "Scripture has two kinds of righteousness in view — the kind people try to produce, which Isaiah calls filthy rags, and the kind God gives. These verses cover both, including what Paul says happened at the cross to trade one for the other.",
  "identity-in-christ": "The New Testament spends more time on who believers are than on what they should do, and puts it in that order on purpose. These verses cover the names scripture gives them: new creature, child of God, chosen, accepted in the beloved.",
  "eternal-life": "Eternal life in scripture starts now rather than at a funeral. Jesus defines it as knowing God, and John says you can know you have it. These verses cover what is promised, who it is promised to, and what it cost.",
  "rest": "Rest in the Bible is commanded before it's earned — God rested first, and then told people to. These verses cover the sabbath, the rest Jesus offers for the soul, and the rest Hebrews says is still waiting.",
  "sickness": "Scripture doesn't treat illness as a verdict on somebody's faith, and Job's friends are in the Bible partly to show that. These verses cover praying for the sick, God's nearness in it, and the comfort written by people who were unwell when they wrote.",
  "suffering": "The Bible never explains suffering away, and its best-known book on the subject ends without an answer to the question. These verses cover what God does in it, what Paul says it produces, and the promise that it doesn't get the last word.",
  "hard-times": "Scripture's promises for hard stretches are mostly about company rather than escape. Through the fire, through the water, through the valley — through is the word that keeps coming back. These verses cover what God says he'll do while it lasts.",
  "waiting-on-god": "Waiting in the Bible is active. It's the kind that keeps expecting him to move, not the kind that gives up and calls it patience. These verses cover renewed strength, waiting on the LORD, and the psalms written by men who were tired of waiting.",
  "doubt": "Scripture handles doubt better than most people expect. Thomas got to touch the wounds. John the Baptist sent men to ask, from prison, and got a kind answer. These verses cover honest questions and what Jude says to do with people who have them.",
  "guilt-and-shame": "The Bible separates guilt, which is about what you did, from shame, which is about who you think you are. These verses cover confession, cleansing, and the line in Romans about there being no condemnation left for people in Christ.",
  "anger": "Scripture doesn't forbid anger outright — be ye angry, and sin not. It puts a clock on it and a limit around it. These verses cover slow to wrath, letting the sun go down, and what Proverbs says a soft answer does.",
  "bitterness": "Hebrews calls bitterness a root, which is the right picture: out of sight, growing, and it comes up eventually. These verses cover letting it go, what Paul lists it alongside, and the forgiveness that is the only real way out of it.",
  "jealousy-and-envy": "Envy in scripture is treated as rot rather than ambition — Proverbs calls it rottenness of the bones. These verses cover coveting, comparison, and what James says shows up wherever envying and strife are.",
  "pride": "Pride is the one sin the Bible says God actively resists. Pride goeth before destruction is a prediction, not an insult. These verses cover what pride does to a person and the grace scripture says is reserved for the humble instead.",
  "gossip": "Proverbs treats gossip as food — talebearer's words go down into the innermost parts. These verses cover the tongue, the damage done with it, and what scripture says about carrying a story that wasn't yours to carry.",
  "judging-others": "Judge not is quoted more often than it's finished. Jesus goes on to talk about a beam and a mote, which makes it about order rather than silence. These verses cover the whole passage and what Paul adds about judging inside the church.",
  "honesty": "Scripture ties honesty to God's own character — lying lips are an abomination, and a just weight is his delight. These verses cover truthfulness in speech, in business, and in the ordinary places where nobody would know.",
  "truth": "Truth in scripture is a person before it's a proposition. Jesus says I am the truth, and then that it sets people free. These verses cover knowing it, walking in it, and worshipping in spirit and in truth.",
  "kindness": "The King James word is often gentleness or tender mercy, and scripture treats it as strength under control rather than softness. These verses cover kindness to neighbors, to enemies, and the kindness of God that Romans says leads people to repentance.",
  "self-control": "Temperance is the last item in the fruit of the Spirit, which places it as something grown rather than forced. These verses cover Proverbs on a city without walls, Paul on running a race, and Peter's list of what to add to faith.",
  "serving-others": "Jesus defined greatness downward and then washed feet to make the point unmistakable. These verses cover serving as the shape of Christian life — the good Samaritan, the least of these, and bearing one another's burdens.",
  "unity": "The New Testament treats unity as something kept rather than manufactured — endeavouring to keep the unity of the Spirit. These verses cover Jesus' prayer the night before he died, Paul on one body, and the psalm about brethren dwelling together.",
  "loving-your-enemies": "This is the command people find hardest, and Jesus gave a reason for it: that ye may be the children of your Father. These verses cover blessing those who curse, overcoming evil with good, and leaving vengeance where scripture says it belongs.",
  "purpose": "Scripture answers the purpose question at two levels — what people are for in general, and what God is doing with one life in particular. These verses cover both, including Jeremiah on being known before birth and Paul on being God's workmanship.",
};
