// Curated data for the Bible + World timeline (scripts/build-chrono.mjs).
// Years are written the human way: negative = BC, positive = AD (no year 0).
// Bible dates follow Ussher / the KJV margin chronology (as Theographic does).
// World dates are the conventional historical dates; build-chrono.mjs
// harmonizes anything earlier than 1650 BC into the post-Flood window and keeps
// the conventional date alongside it.

// ── Books: [name, author, written (year or [from, to]), note] ────────────────
export const BOOKS = [
  ["Genesis", "Moses", [-1491, -1451]],
  ["Exodus", "Moses", [-1491, -1451]],
  ["Leviticus", "Moses", -1490],
  ["Numbers", "Moses", [-1490, -1451]],
  ["Deuteronomy", "Moses", -1451],
  ["Joshua", "Joshua", -1427],
  ["Judges", "Samuel (traditionally)", -1050],
  ["Ruth", "Samuel (traditionally)", -1050],
  ["1 Samuel", "Samuel, Nathan and Gad", [-1060, -1015]],
  ["2 Samuel", "Nathan and Gad", [-1015, -1000]],
  ["1 Kings", "Jeremiah (traditionally)", [-590, -560]],
  ["2 Kings", "Jeremiah (traditionally)", [-590, -560]],
  ["1 Chronicles", "Ezra (traditionally)", [-450, -430]],
  ["2 Chronicles", "Ezra (traditionally)", [-450, -430]],
  ["Ezra", "Ezra", [-456, -440]],
  ["Nehemiah", "Nehemiah", [-432, -420]],
  ["Esther", "Mordecai (traditionally)", [-450, -430]],
  ["Job", "Unknown (Moses, by tradition)", -1520],
  ["Psalms", "David and others", [-1451, -450]],
  ["Proverbs", "Solomon and others", [-1000, -700]],
  ["Ecclesiastes", "Solomon", -977],
  ["Song of Solomon", "Solomon", -1014],
  ["Isaiah", "Isaiah", [-760, -698]],
  ["Jeremiah", "Jeremiah", [-629, -586]],
  ["Lamentations", "Jeremiah", -588],
  ["Ezekiel", "Ezekiel", [-595, -574]],
  ["Daniel", "Daniel", [-606, -534]],
  ["Hosea", "Hosea", [-785, -725]],
  ["Joel", "Joel", -800],
  ["Amos", "Amos", -787],
  ["Obadiah", "Obadiah", -587],
  ["Jonah", "Jonah", -862],
  ["Micah", "Micah", [-750, -710]],
  ["Nahum", "Nahum", -713],
  ["Habakkuk", "Habakkuk", -626],
  ["Zephaniah", "Zephaniah", -630],
  ["Haggai", "Haggai", -520],
  ["Zechariah", "Zechariah", [-520, -487]],
  ["Malachi", "Malachi", -397],
  ["Matthew", "Matthew", [50, 60]],
  ["Mark", "John Mark", [55, 65]],
  ["Luke", "Luke", [59, 62]],
  ["John", "John the apostle", [85, 90]],
  ["Acts", "Luke", [61, 63]],
  ["Romans", "Paul", 57],
  ["1 Corinthians", "Paul", 55],
  ["2 Corinthians", "Paul", 56],
  ["Galatians", "Paul", 49],
  ["Ephesians", "Paul", 60],
  ["Philippians", "Paul", 61],
  ["Colossians", "Paul", 60],
  ["1 Thessalonians", "Paul", 51],
  ["2 Thessalonians", "Paul", 52],
  ["1 Timothy", "Paul", 63],
  ["2 Timothy", "Paul", 67],
  ["Titus", "Paul", 63],
  ["Philemon", "Paul", 60],
  ["Hebrews", "Unknown", [64, 68]],
  ["James", "James, the Lord's brother", [45, 49]],
  ["1 Peter", "Peter", [62, 64]],
  ["2 Peter", "Peter", [65, 68]],
  ["1 John", "John the apostle", [85, 95]],
  ["2 John", "John the apostle", [85, 95]],
  ["3 John", "John the apostle", [85, 95]],
  ["Jude", "Jude, the Lord's brother", [65, 80]],
  ["Revelation", "John the apostle", [95, 96]],
];

// ── Bible people: [slug, name, from, to, role] ───────────────────────────────
// from/to = lifetime where Scripture gives it, otherwise the years they are
// active in the text (reigns for kings, ministries for prophets).
export const PEOPLE = [
  ["adam_78", "Adam", -4004, -3074, "first man"],
  ["seth_2504", "Seth", -3874, -2962, "patriarch"],
  ["enoch_1192", "Enoch", -3382, -3017, "walked with God"],
  ["methuselah_2042", "Methuselah", -3317, -2348, "patriarch"],
  ["noah_2210", "Noah", -2948, -1998, "patriarch"],
  ["shem_2613", "Shem", -2446, -1846, "patriarch"],
  ["abraham_58", "Abraham", -1996, -1821, "patriarch"],
  ["sarah_2473", "Sarah", -1986, -1859, "matriarch"],
  ["lot_1830", "Lot", -1921, -1897, "Abraham's nephew"],
  ["melchisedec_1991", "Melchizedek", -1913, -1913, "priest-king of Salem"],
  ["isaac_616", "Isaac", -1896, -1716, "patriarch"],
  ["israel_682", "Jacob (Israel)", -1836, -1689, "patriarch"],
  ["joseph_1710", "Joseph", -1745, -1635, "ruler in Egypt"],
  ["job_1639", "Job", -1720, -1580, "man of Uz"],
  ["moses_2108", "Moses", -1571, -1451, "lawgiver"],
  ["aaron_1", "Aaron", -1574, -1452, "high priest"],
  ["miriam_2087", "Miriam", -1578, -1452, "prophetess"],
  ["joshua_1727", "Joshua", -1536, -1426, "leader"],
  ["caleb_537", "Caleb", -1530, -1420, "spy and leader"],
  ["deborah_997", "Deborah", -1285, -1245, "judge"],
  ["gideon_1314", "Gideon", -1249, -1209, "judge"],
  ["eli_1072", "Eli", -1239, -1141, "priest and judge"],
  ["samson_2468", "Samson", -1136, -1117, "judge"],
  ["boaz_519", "Boaz", -1180, -1100, "kinsman-redeemer"],
  ["ruth_2450", "Ruth", -1150, -1090, "Moabitess"],
  ["samuel_2469", "Samuel", -1171, -1060, "prophet and judge"],
  ["saul_2478", "Saul", -1095, -1056, "king of Israel"],
  ["david_994", "David", -1085, -1015, "king of Israel"],
  ["gad_1263", "Gad", -1062, -1017, "seer"],
  ["nathan_2153", "Nathan", -1050, -1000, "prophet"],
  ["solomon_2762", "Solomon", -1033, -975, "king of Israel"],
  ["rehoboam_2412", "Rehoboam", -975, -958, "king of Judah"],
  ["jeroboam_872", "Jeroboam I", -975, -954, "king of Israel"],
  ["asa_318", "Asa", -955, -914, "king of Judah"],
  ["ahab_113", "Ahab", -918, -897, "king of Israel"],
  ["jezebel_1605", "Jezebel", -918, -884, "queen of Israel"],
  ["jehoshaphat_808", "Jehoshaphat", -914, -889, "king of Judah"],
  ["elijah_1131", "Elijah", -910, -896, "prophet"],
  ["elisha_1153", "Elisha", -899, -838, "prophet"],
  ["jehu_817", "Jehu", -884, -856, "king of Israel"],
  ["joash_1632", "Joash", -878, -839, "king of Judah"],
  ["jonah_1689", "Jonah", -862, -825, "prophet"],
  ["joel_1660", "Joel", -810, -790, "prophet"],
  ["jeroboam_873", "Jeroboam II", -825, -784, "king of Israel"],
  ["uzziah_375", "Uzziah", -810, -758, "king of Judah"],
  ["amos_238", "Amos", -790, -780, "prophet"],
  ["hosea_1555", "Hosea", -785, -725, "prophet"],
  ["isaiah_617", "Isaiah", -760, -698, "prophet"],
  ["micah_2053", "Micah", -750, -710, "prophet"],
  ["jotham_1735", "Jotham", -758, -742, "king of Judah"],
  ["ahaz_118", "Ahaz", -742, -726, "king of Judah"],
  ["hoshea_1559", "Hoshea", -730, -721, "last king of Israel"],
  ["hezekiah_1512", "Hezekiah", -726, -697, "king of Judah"],
  ["manasseh_1930", "Manasseh", -698, -643, "king of Judah"],
  ["nahum_2145", "Nahum", -720, -698, "prophet"],
  ["josiah_1730", "Josiah", -649, -610, "king of Judah"],
  ["zephaniah_3040", "Zephaniah", -635, -620, "prophet"],
  ["jeremiah_853", "Jeremiah", -629, -580, "prophet"],
  ["habakkuk_1334", "Habakkuk", -630, -600, "prophet"],
  ["jehoiakim_1085", "Jehoiakim", -610, -599, "king of Judah"],
  ["jehoiachin_791", "Jehoiachin", -599, -562, "king of Judah"],
  ["zedekiah_1950", "Zedekiah", -599, -588, "last king of Judah"],
  ["daniel_975", "Daniel", -620, -534, "prophet in Babylon"],
  ["ezekiel_1237", "Ezekiel", -622, -570, "prophet in exile"],
  ["baruch_410", "Baruch", -610, -580, "Jeremiah's scribe"],
  ["obadiah_2226", "Obadiah", -590, -580, "prophet"],
  ["nebuchadnezzar_2167", "Nebuchadnezzar", -605, -562, "king of Babylon"],
  ["belshazzar_437", "Belshazzar", -553, -538, "ruler of Babylon"],
  ["darius_980", "Darius the Mede", -600, -536, "ruler of Babylon"],
  ["cyrus_968", "Cyrus", -559, -530, "king of Persia"],
  ["zerubbabel_3054", "Zerubbabel", -536, -515, "governor of Judah"],
  ["haggai_1349", "Haggai", -525, -515, "prophet"],
  ["zechariah_3016", "Zechariah", -525, -487, "prophet"],
  ["darius_978", "Darius I", -522, -486, "king of Persia"],
  ["esther_1343", "Esther", -480, -450, "queen of Persia"],
  ["mordecai_2107", "Mordecai", -490, -450, "Esther's cousin"],
  ["ahasuerus_117", "Ahasuerus", -486, -465, "king of Persia"],
  ["ezra_1245", "Ezra", -480, -440, "priest and scribe"],
  ["artaxerxes_314", "Artaxerxes", -465, -424, "king of Persia"],
  ["nehemiah_2172", "Nehemiah", -446, -420, "governor of Judah"],
  ["malachi_1899", "Malachi", -410, -397, "prophet"],
  ["herod_1504", "Herod the Great", -37, -4, "king of Judea"],
  ["mary_1938", "Mary", -20, 33, "mother of Jesus"],
  ["john_1676", "John the Baptist", -5, 29, "forerunner"],
  ["jesus_905", "Jesus Christ", -4, 33, "the Son of God"],
  ["herod_1505", "Herod Antipas", -4, 39, "tetrarch of Galilee"],
  ["pilate_2365", "Pontius Pilate", 26, 36, "governor of Judea"],
  ["peter_2745", "Simon Peter", 27, 67, "apostle"],
  ["john_1677", "John the apostle", 27, 98, "apostle"],
  ["james_717", "James son of Zebedee", 27, 44, "apostle"],
  ["james_719", "James the Lord's brother", 30, 62, "leader in Jerusalem"],
  ["stephen_2802", "Stephen", 33, 34, "first martyr"],
  ["paul_2479", "Paul", 5, 67, "apostle"],
  ["barnabas_1722", "Barnabas", 33, 60, "missionary"],
  ["herod_1506", "Herod Agrippa I", 37, 44, "king of Judea"],
  ["mark_1679", "John Mark", 44, 68, "gospel writer"],
  ["silas_2740", "Silas", 49, 55, "missionary"],
  ["timotheus_2863", "Timothy", 48, 67, "pastor"],
  ["titus_2869", "Titus", 49, 67, "pastor"],
  ["luke_1836", "Luke", 49, 85, "physician and historian"],
  ["priscilla_2370", "Priscilla", 49, 60, "teacher"],
  ["apollos_276", "Apollos", 52, 60, "preacher"],
  ["felix_1257", "Felix", 52, 59, "governor of Judea"],
  ["portius_2367", "Porcius Festus", 59, 62, "governor of Judea"],
  ["jude_1756", "Jude", 30, 80, "the Lord's brother"],
];

// ── Bible events Theographic doesn't cover (mostly the exile and return) ─────
// [year, title, ref, [slugs]]
export const BIBLE_EXTRA = [
  [-606, "Daniel and his friends taken to Babylon", "Daniel 1:6", ["daniel_975", "nebuchadnezzar_2167"]],
  [-603, "Nebuchadnezzar's dream of the great image", "Daniel 2:31", ["daniel_975", "nebuchadnezzar_2167"]],
  [-599, "Jehoiachin and Ezekiel carried to Babylon", "2 Kings 24:15", ["jehoiachin_791", "ezekiel_1237"]],
  [-588, "Jerusalem falls; Solomon's Temple burned", "2 Kings 25:9", ["zedekiah_1950", "nebuchadnezzar_2167", "jeremiah_853"]],
  [-580, "Shadrach, Meshach and Abednego in the fiery furnace", "Daniel 3:23", ["nebuchadnezzar_2167"]],
  [-569, "Nebuchadnezzar humbled", "Daniel 4:33", ["nebuchadnezzar_2167", "daniel_975"]],
  [-562, "Jehoiachin released from prison", "2 Kings 25:27", ["jehoiachin_791", "evil-merodach_1233"]],
  [-538, "The writing on the wall; Babylon falls", "Daniel 5:25", ["belshazzar_437", "daniel_975"]],
  [-537, "Daniel in the lions' den", "Daniel 6:16", ["daniel_975", "darius_980"]],
  [-536, "Cyrus decrees the return to Jerusalem", "Ezra 1:1", ["cyrus_968"]],
  [-535, "Foundation of the second Temple laid", "Ezra 3:10", ["zerubbabel_3054"]],
  [-520, "Temple building resumes", "Ezra 5:1", ["haggai_1349", "zechariah_3016", "zerubbabel_3054"]],
  [-515, "The second Temple completed", "Ezra 6:15", ["darius_978"]],
  [-462, "Esther made queen", "Esther 2:17", ["esther_1343", "ahasuerus_117"]],
  [-452, "Feast of Purim; the Jews delivered", "Esther 9:26", ["esther_1343", "mordecai_2107"]],
  [-457, "Ezra returns to Jerusalem", "Ezra 7:8", ["ezra_1245", "artaxerxes_314"]],
  [-445, "Nehemiah rebuilds the walls of Jerusalem", "Nehemiah 6:15", ["nehemiah_2172"]],
  [-445, "Ezra reads the Law to the people", "Nehemiah 8:3", ["ezra_1245", "nehemiah_2172"]],
];

// ── World history: conventional dates ────────────────────────────────────────
// r: region (ne Near East · eg Egypt & Africa · med Greece & Rome · as Asia · wo Europe & Americas)
// k: power (an empire/kingdom span) · event · person · work (building, writing, invention)
// y: year, or [start, end]; p: Bible person slug; ref: where Scripture touches it
// h: harmonized date for a synchronism with a Bible event, where Ussher's dates for
//    the kings run ahead of the Assyrian/Egyptian ones (the conventional date is still shown)
export const WORLD = [
  // Near East
  { t: "Sumerian city-states", y: [-3200, -2350], r: "ne", k: "power", d: "Uruk, Ur and Eridu, among the first cities, rise in the land of Shinar (southern Iraq)." },
  { t: "Writing begins", y: -3200, r: "ne", k: "work", d: "Cuneiform wedge-writing on clay tablets appears in Sumer." },
  { t: "Akkadian Empire", y: [-2334, -2154], r: "ne", k: "power", d: "Sargon of Akkad forges the first great empire of Mesopotamia." },
  { t: "Epic of Gilgamesh", y: -2100, r: "ne", k: "work", d: "The Sumerian epic includes a flood story that echoes Genesis 6–9." },
  { t: "Third Dynasty of Ur", y: [-2112, -2004], r: "ne", k: "power", d: "Ur rebuilt with its great ziggurat. Abraham's home city.", ref: "Genesis 11:31" },
  { t: "Old Babylonian Empire", y: [-1894, -1595], r: "ne", k: "power", d: "Babylon rises to power along the Euphrates." },
  { t: "Code of Hammurabi", y: -1754, r: "ne", k: "work", d: "Babylon's king carves 282 laws in stone, one of the oldest law codes." },
  { t: "Hittite Empire", y: [-1650, -1180], r: "ne", k: "power", d: "The Hittites of Anatolia rival Egypt. The Bible's 'sons of Heth'.", ref: "Genesis 23:10" },
  { t: "Amarna letters", y: -1350, r: "ne", k: "work", d: "Canaanite kings write to Pharaoh, complaining of raiders called 'Habiru'." },
  { t: "Sea Peoples and the Bronze Age collapse", y: -1177, r: "ne", k: "event", d: "Great kingdoms fall; the Philistines settle on Canaan's coast." },
  { t: "Phoenician alphabet", y: -1050, r: "ne", k: "work", d: "A 22-letter alphabet from Tyre and Sidon, ancestor of Hebrew, Greek and Latin letters." },
  { t: "Hiram, king of Tyre", y: [-980, -947], r: "ne", k: "person", p: "hiram_1532", h: [-1045, -1000], d: "Sends cedar and craftsmen for David's palace and Solomon's Temple.", ref: "1 Kings 5:1" },
  { t: "Neo-Assyrian Empire", y: [-911, -609], r: "ne", k: "power", d: "Assyria's armies dominate the Near East from Nineveh." },
  { t: "Battle of Qarqar", y: -853, h: -898, r: "ne", k: "event", d: "Assyria's own records list 'Ahab the Israelite' with 2,000 chariots.", p: "ahab_113" },
  { t: "Mesha Stele (Moabite Stone)", y: -840, h: -895, r: "ne", k: "work", d: "Mesha king of Moab boasts of throwing off Israel's rule, as in 2 Kings 3.", ref: "2 Kings 3:4" },
  { t: "Black Obelisk", y: -841, h: -880, r: "ne", k: "work", d: "Shows Jehu of Israel bowing before Shalmaneser III, the only image of an Israelite king.", p: "jehu_817" },
  { t: "Tiglath-pileser III", y: [-745, -727], r: "ne", k: "person", p: "tilgath-pilneser_2376", d: "Assyrian king ('Pul') who takes tribute from Israel and deports Galileans.", ref: "2 Kings 15:29" },
  { t: "Shalmaneser V", y: [-727, -722], r: "ne", k: "person", p: "shalmaneser_2529", d: "Besieges Samaria for three years.", ref: "2 Kings 17:5" },
  { t: "Assyria takes Samaria", y: -722, r: "ne", k: "event", d: "Sargon II deports Israel's ten northern tribes.", ref: "2 Kings 17:6" },
  { t: "Merodach-baladan", y: [-722, -710], r: "ne", k: "person", p: "merodach-baladan_483", d: "Babylonian rebel king who sends envoys to Hezekiah.", ref: "Isaiah 39:1" },
  { t: "Sennacherib", y: [-705, -681], r: "ne", k: "person", p: "sennacherib_2489", d: "Assyrian king whose prism says he shut Hezekiah up 'like a bird in a cage'.", ref: "2 Kings 18:13" },
  { t: "Siege of Lachish", y: -701, r: "ne", k: "event", d: "Sennacherib's palace reliefs show the capture of Judah's second city.", ref: "2 Kings 18:14" },
  { t: "Siloam inscription", y: -701, r: "ne", k: "work", d: "Hezekiah's tunnel brings water inside Jerusalem's walls.", ref: "2 Kings 20:20" },
  { t: "Esarhaddon", y: [-681, -669], r: "ne", k: "person", p: "esar-haddon_1215", d: "Sennacherib's son, who succeeds him after his murder.", ref: "2 Kings 19:37" },
  { t: "Ashurbanipal's library", y: -650, r: "ne", k: "work", d: "The last great Assyrian king gathers 30,000 clay tablets at Nineveh." },
  { t: "Neo-Babylonian Empire", y: [-626, -539], r: "ne", k: "power", d: "Babylon throws off Assyria and becomes the head of gold.", ref: "Daniel 2:38" },
  { t: "Fall of Nineveh", y: -612, r: "ne", k: "event", d: "Babylonians and Medes destroy Assyria's capital, as Nahum foretold.", ref: "Nahum 3:7" },
  { t: "Battle of Carchemish", y: -605, r: "ne", k: "event", d: "Nebuchadnezzar defeats Pharaoh Necho; Babylon rules the region.", ref: "Jeremiah 46:2" },
  { t: "Nebuchadnezzar II", y: [-605, -562], r: "ne", k: "person", p: "nebuchadnezzar_2167", d: "Builds the Ishtar Gate and famed gardens of Babylon; takes Jerusalem.", ref: "Daniel 4:30" },
  { t: "Ishtar Gate", y: -575, r: "ne", k: "work", d: "Blue-glazed brick gate of lions and dragons at Babylon." },
  { t: "Persian Empire", y: [-550, -330], r: "ne", k: "power", d: "Cyrus unites the Medes and Persians: the largest empire yet.", ref: "Daniel 8:20" },
  { t: "Cyrus takes Babylon", y: -539, r: "ne", k: "event", p: "cyrus_968", d: "The Cyrus Cylinder records his policy of sending exiles home.", ref: "Isaiah 45:1" },
  { t: "Behistun inscription", y: -520, r: "ne", k: "work", d: "Darius I carves his deeds on a cliff in three languages, the key to reading cuneiform.", p: "darius_978" },
  { t: "Persepolis built", y: -518, r: "ne", k: "work", d: "Darius begins the ceremonial capital of Persia." },
  { t: "Xerxes (Ahasuerus)", y: [-486, -465], r: "ne", k: "person", p: "ahasuerus_117", d: "Persian king who invades Greece. Widely identified with Esther's Ahasuerus.", ref: "Esther 1:1" },
  { t: "Artaxerxes I", y: [-465, -424], r: "ne", k: "person", p: "artaxerxes_314", d: "Sends Ezra and Nehemiah to Jerusalem.", ref: "Nehemiah 2:1" },
  { t: "Seleucid Empire", y: [-312, -63], r: "ne", k: "power", d: "A Greek dynasty rules Syria and Babylon after Alexander: Daniel's 'king of the north'.", ref: "Daniel 11:6" },
  { t: "Parthian Empire", y: [-247, 224], r: "ne", k: "power", d: "Iranian rivals of Rome. Parthians hear the gospel at Pentecost.", ref: "Acts 2:9" },
  { t: "Antiochus IV desecrates the Temple", y: -167, r: "ne", k: "event", d: "A Greek king sets up an idol altar in the Temple: the 'abomination' of Daniel 11:31.", ref: "Daniel 11:31" },
  { t: "Maccabean revolt", y: [-167, -160], r: "ne", k: "event", d: "Judas Maccabeus retakes Jerusalem; the Temple is rededicated (Hanukkah).", ref: "John 10:22" },
  { t: "Hasmonean kingdom", y: [-140, -37], r: "ne", k: "power", d: "Judea independent under Jewish priest-kings for the last time before Rome." },
  { t: "Qumran community", y: [-150, 68], r: "ne", k: "work", d: "Copies the Dead Sea Scrolls, including a complete Isaiah scroll." },
  { t: "Pompey takes Jerusalem", y: -63, r: "ne", k: "event", d: "Judea comes under Roman control." },
  { t: "Herod the Great", y: [-37, -4], r: "ne", k: "person", p: "herod_1504", d: "Rome's king of Judea rebuilds the Temple and builds Masada and Caesarea.", ref: "Matthew 2:1" },
  { t: "Herod's Temple rebuilding", y: -20, r: "ne", k: "work", d: "The Temple expansion that Jesus knew, still underway in his day.", ref: "John 2:20" },
  { t: "Jewish revolt against Rome", y: [66, 73], r: "ne", k: "event", d: "Judea rises against Rome; Jerusalem is besieged." },
  { t: "Jerusalem and the Temple destroyed", y: 70, r: "ne", k: "event", d: "Titus burns the Temple, as Jesus foretold.", ref: "Matthew 24:2" },
  { t: "Fall of Masada", y: 73, r: "ne", k: "event", d: "The last Jewish stronghold falls to Rome." },

  // Egypt & Africa
  { t: "Egypt united", y: -3100, r: "eg", k: "event", d: "Upper and Lower Egypt join under one king. Egypt is called 'Mizraim' in Hebrew.", ref: "Genesis 10:6" },
  { t: "Old Kingdom of Egypt", y: [-2686, -2181], r: "eg", k: "power", d: "The age of the pyramids." },
  { t: "Step Pyramid of Djoser", y: -2670, r: "eg", k: "work", d: "The first large stone building in the world." },
  { t: "Great Pyramid of Giza", y: -2560, r: "eg", k: "work", d: "Built for Pharaoh Khufu. The tallest structure on earth for nearly 4,000 years." },
  { t: "Middle Kingdom of Egypt", y: [-2055, -1650], r: "eg", k: "power", d: "Egypt reunited, with a strong central government and granaries." },
  { t: "Hyksos rule northern Egypt", y: [-1650, -1550], r: "eg", k: "power", d: "Semitic 'rulers of foreign lands' govern from the Nile Delta." },
  { t: "New Kingdom of Egypt", y: [-1550, -1070], r: "eg", k: "power", d: "Egypt's imperial age of chariots, conquests and the Valley of the Kings." },
  { t: "Hatshepsut", y: [-1479, -1458], r: "eg", k: "person", d: "A woman rules Egypt as Pharaoh." },
  { t: "Thutmose III", y: [-1479, -1425], r: "eg", k: "person", d: "Egypt's greatest warrior pharaoh campaigns through Canaan." },
  { t: "Akhenaten", y: [-1353, -1336], r: "eg", k: "person", d: "Pharaoh who orders worship of the sun-disk Aten alone." },
  { t: "Tutankhamun", y: [-1332, -1323], r: "eg", k: "person", d: "Boy king whose untouched tomb was found in 1922." },
  { t: "Ramesses II", y: [-1279, -1213], r: "eg", k: "person", d: "Builds Abu Simbel and makes the first known peace treaty, with the Hittites." },
  { t: "Merneptah Stele", y: -1208, r: "eg", k: "work", d: "Earliest mention of 'Israel' outside the Bible: a people already living in Canaan." },
  { t: "Kingdom of Kush", y: [-1070, 350], r: "eg", k: "power", d: "Nubian kingdom south of Egypt: the Bible's Ethiopia.", ref: "Acts 8:27" },
  { t: "Shishak invades Judah", y: -925, h: -971, r: "eg", k: "event", p: "shishak_2712", d: "Pharaoh Shoshenq I lists conquered towns of Israel and Judah on a temple wall at Karnak.", ref: "1 Kings 14:25" },
  { t: "Kushite pharaohs rule Egypt", y: [-744, -656], r: "eg", k: "power", d: "Nubian kings like Taharqa (Tirhakah) rule Egypt.", ref: "2 Kings 19:9" },
  { t: "Pharaoh Necho kills Josiah", y: -609, r: "eg", k: "event", d: "Necho II marches north to aid Assyria; Josiah falls at Megiddo.", ref: "2 Kings 23:29" },
  { t: "Pharaoh Hophra", y: [-589, -570], r: "eg", k: "person", d: "Egyptian king Jeremiah warned would fall to his enemies.", ref: "Jeremiah 44:30" },
  { t: "Ptolemaic Egypt", y: [-305, -30], r: "eg", k: "power", d: "Greek kings rule Egypt from Alexandria: Daniel's 'king of the south'.", ref: "Daniel 11:5" },
  { t: "Library of Alexandria", y: -285, r: "eg", k: "work", d: "The ancient world's greatest library." },
  { t: "Septuagint", y: -250, r: "eg", k: "work", d: "Jewish scholars in Alexandria translate the Old Testament into Greek. Often quoted in the New Testament." },
  { t: "Cleopatra dies; Rome takes Egypt", y: -30, r: "eg", k: "event", d: "The last Pharaoh's death ends 3,000 years of Egyptian kingdoms." },

  // Greece & Rome
  { t: "Minoan Crete", y: [-2700, -1450], r: "med", k: "power", d: "Palace culture of Knossos. Crete is the Bible's Caphtor, homeland of the Philistines.", ref: "Amos 9:7" },
  { t: "Mycenaean Greece", y: [-1600, -1100], r: "med", k: "power", d: "Bronze Age warrior kingdoms of Homer's heroes." },
  { t: "Trojan War (traditional date)", y: -1184, r: "med", k: "event", d: "The war later sung by Homer." },
  { t: "Carthage founded", y: -814, r: "med", k: "event", d: "Phoenicians from Tyre plant a colony in North Africa." },
  { t: "First Olympic Games", y: -776, r: "med", k: "event", d: "Greek athletes compete at Olympia in honor of Zeus." },
  { t: "Rome founded (traditional)", y: -753, r: "med", k: "event", d: "Romulus founds the city on the Tiber, the Romans said." },
  { t: "Homer's Iliad and Odyssey", y: -750, r: "med", k: "work", d: "Greece's great epic poems are composed." },
  { t: "Solon's laws in Athens", y: -594, r: "med", k: "event", d: "Athens reforms its laws and cancels debts." },
  { t: "Pythagoras", y: [-570, -495], r: "med", k: "person", d: "Greek philosopher and mathematician." },
  { t: "Roman Republic", y: [-509, -27], r: "med", k: "power", d: "Rome expels its kings and is governed by consuls and a Senate." },
  { t: "Athenian democracy", y: -508, r: "med", k: "event", d: "Cleisthenes gives power to the citizens' assembly." },
  { t: "Battle of Marathon", y: -490, r: "med", k: "event", d: "Athens defeats Darius's Persian army." },
  { t: "Thermopylae and Salamis", y: -480, r: "med", k: "event", d: "Greeks stop Xerxes's invasion of Greece." },
  { t: "Golden Age of Athens", y: [-461, -429], r: "med", k: "power", d: "Under Pericles, Athens builds the Parthenon while Nehemiah rebuilds Jerusalem." },
  { t: "Parthenon built", y: [-447, -432], r: "med", k: "work", d: "Temple of Athena on the Acropolis." },
  { t: "Herodotus", y: -430, r: "med", k: "person", d: "The 'Father of History' writes about the Persian wars." },
  { t: "Socrates executed", y: -399, r: "med", k: "event", d: "Athens puts its greatest philosopher to death." },
  { t: "Plato and Aristotle", y: [-387, -322], r: "med", k: "person", d: "Plato's Academy and Aristotle's Lyceum shape Western thought." },
  { t: "Alexander the Great", y: [-336, -323], r: "med", k: "person", d: "Conquers Persia to India. The 'notable horn' of Daniel's vision.", ref: "Daniel 8:5" },
  { t: "Alexander's empire divided", y: -301, r: "med", k: "event", d: "After Alexander's death his generals split his empire four ways.", ref: "Daniel 8:22" },
  { t: "Punic Wars", y: [-264, -146], r: "med", k: "event", d: "Rome and Carthage fight for the Mediterranean; Hannibal crosses the Alps." },
  { t: "Rome destroys Carthage and Corinth", y: -146, r: "med", k: "event", d: "Rome becomes master of the Mediterranean." },
  { t: "Julius Caesar assassinated", y: -44, r: "med", k: "event", d: "Caesar is killed in the Senate, and civil war follows." },
  { t: "Roman Empire", y: [-27, 476], r: "med", k: "power", d: "Augustus becomes the first emperor. Daniel's fourth kingdom, 'strong as iron'.", ref: "Daniel 2:40" },
  { t: "Caesar Augustus", y: [-27, 14], r: "med", k: "person", p: "augustus_366", d: "His census brings Joseph and Mary to Bethlehem.", ref: "Luke 2:1" },
  { t: "Pax Romana", y: [-27, 180], r: "med", k: "event", d: "Two centuries of Roman peace and roads that carry the gospel." },
  { t: "Tiberius", y: [14, 37], r: "med", k: "person", p: "tiberius_2852", d: "Emperor during John the Baptist's and Jesus's ministries.", ref: "Luke 3:1" },
  { t: "Caligula", y: [37, 41], r: "med", k: "person", d: "Orders his statue placed in the Temple, but dies before it is done." },
  { t: "Claudius", y: [41, 54], r: "med", k: "person", p: "claudius_947", d: "Expels the Jews from Rome, bringing Aquila and Priscilla to Corinth.", ref: "Acts 18:2" },
  { t: "Rome invades Britain", y: 43, r: "wo", k: "event", d: "Claudius adds Britain to the empire." },
  { t: "Gallio, proconsul of Achaia", y: 51, r: "med", k: "person", p: "gallio_1275", d: "An inscription at Delphi dates his term, anchoring Paul's timeline.", ref: "Acts 18:12" },
  { t: "Nero", y: [54, 68], r: "med", k: "person", d: "The Caesar to whom Paul appealed; later persecutes Christians.", ref: "Acts 25:11" },
  { t: "Great Fire of Rome", y: 64, r: "med", k: "event", d: "Nero blames the Christians and begins the first persecution." },
  { t: "Vesuvius buries Pompeii", y: 79, r: "med", k: "event", d: "A volcanic eruption preserves a Roman town." },
  { t: "Colosseum opens", y: 80, r: "med", k: "work", d: "Rome's great amphitheater, built with spoils from Jerusalem." },
  { t: "Domitian", y: [81, 96], r: "med", k: "person", d: "Demands worship as 'lord and god'. By tradition he exiles John to Patmos.", ref: "Revelation 1:9" },

  // Asia
  { t: "Indus Valley civilization", y: [-2600, -1900], r: "as", k: "power", d: "Planned cities like Mohenjo-daro with drains and baths." },
  { t: "Xia dynasty (traditional)", y: [-2070, -1600], r: "as", k: "power", d: "China's first dynasty in its own histories." },
  { t: "Shang dynasty", y: [-1600, -1046], r: "as", k: "power", d: "Bronze-working Chinese kingdom; the earliest Chinese writing, on oracle bones." },
  { t: "Vedic India", y: [-1500, -500], r: "as", k: "power", d: "The Vedas, India's oldest scriptures, are composed." },
  { t: "Zhou dynasty", y: [-1046, -256], r: "as", k: "power", d: "China's longest dynasty and the 'Mandate of Heaven'." },
  { t: "Buddha", y: [-563, -483], r: "as", k: "person", d: "Siddhartha Gautama founds Buddhism in northern India." },
  { t: "Confucius", y: [-551, -479], r: "as", k: "person", d: "China's great teacher, living as the Jews returned from exile." },
  { t: "Mauryan Empire", y: [-322, -185], r: "as", k: "power", d: "The first empire over most of India." },
  { t: "Ashoka", y: [-268, -232], r: "as", k: "person", d: "Mauryan emperor who carves edicts across India." },
  { t: "Qin unites China", y: -221, r: "as", k: "event", d: "The first emperor, Qin Shi Huang, joins the Great Wall and is buried with a terracotta army." },
  { t: "Han dynasty", y: [-206, 220], r: "as", k: "power", d: "A golden age for China, whose silk reaches Rome." },
  { t: "Silk Road opens", y: -130, r: "as", k: "event", d: "Trade routes link China with Persia and the Mediterranean." },
  { t: "Paper invented", y: 105, r: "as", k: "work", d: "Cai Lun of Han China perfects papermaking." },

  // Europe & the Americas
  { t: "Stonehenge", y: [-3000, -2000], r: "wo", k: "work", d: "Great stone circle raised on Salisbury Plain, England." },
  { t: "Olmec civilization", y: [-1200, -400], r: "wo", k: "power", d: "Mexico's first civilization, known for colossal stone heads." },
  { t: "Celtic Iron Age", y: [-800, -50], r: "wo", k: "power", d: "Celtic tribes spread across Europe from the Alps." },
  { t: "Maya city of El Mirador", y: -300, r: "wo", k: "work", d: "Huge pyramids rise in the Guatemalan jungle." },
  { t: "Caesar lands in Britain", y: -55, r: "wo", k: "event", d: "Rome's first contact with Britain." },
  { t: "Teotihuacan", y: [-100, 550], r: "wo", k: "power", d: "Great city of the Pyramids of the Sun and Moon in Mexico." },
];

export const ERAS = [
  { name: "Creation to the Flood", from: -4004, to: -2349 },
  { name: "The Patriarchs", from: -2348, to: -1707 },
  { name: "Egypt and the Exodus", from: -1706, to: -1452 },
  { name: "Conquest and the Judges", from: -1451, to: -1096 },
  { name: "The Kingdom of Israel", from: -1095, to: -976 },
  { name: "The Divided Kingdom", from: -975, to: -587 },
  { name: "Exile and Return", from: -586, to: -400 },
  { name: "Between the Testaments", from: -399, to: -6 },
  { name: "The Life of Christ", from: -5, to: 33 },
  { name: "The Early Church", from: 34, to: 100 },
];
